<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ListDropdownsTableSeeder extends Seeder
{
    public function run()
    {
        \DB::table('list_dropdowns')->delete();

        \DB::table('list_dropdowns')->insert([
            [
                'id' => 1,
                'name' => 'n/a',
                'classification' => 'n/a',
                'type' => 'n/a',
                'color' => 'n/a',
                'others' => 'n/a',
                'is_active' => 1,
            ],
            [
                'id' => 2,
                'name' => 'Office of the Regional Director',
                'classification' => 'Division',
                'type' => 'Main',
                'color' => 'n/a',
                'others' => 'ORD',
                'is_active' => 1,
            ],
            [
                'id' => 3,
                'name' => 'Finance and Administrative Support Services',
                'classification' => 'Division',
                'type' => 'Main',
                'color' => 'n/a',
                'others' => 'FASS',
                'is_active' => 1,
            ],
            [
                'id' => 4,
                'name' => 'Technical Operations Services',
                'classification' => 'Division',
                'type' => 'Main',
                'color' => 'n/a',
                'others' => 'TOS',
                'is_active' => 1,
            ],
            [
                'id' => 5,
                'name' => 'Regional Office',
                'classification' => 'Station',
                'type' => 'Regional Office',
                'color' => 'n/a',
                'others' => 'RO-IX',
                'is_active' => 1,
            ],
            [
                'id' => 6,
                'name' => 'Zamboanga Sibugay',
                'classification' => 'Station',
                'type' => 'Provincial Science and Technology Office',
                'color' => 'n/a',
                'others' => 'PSTO-ZSP',
                'is_active' => 1,
            ],
            [
                'id' => 7,
                'name' => 'Zamboanga Del Norte',
                'classification' => 'Station',
                'type' => 'Provincial Science and Technology Office',
                'color' => 'n/a',
                'others' => 'PSTO-ZDN',
                'is_active' => 1,
            ],
            [
                'id' => 8,
                'name' => 'Zamboanga Del Sur',
                'classification' => 'Station',
                'type' => 'Provincial Science and Technology Office',
                'color' => 'n/a',
                'others' => 'PSTO-ZDS',
                'is_active' => 1,
            ],
            [
                'id' => 9,
                'name' => 'Zamboanga City / Isabela City',
                'classification' => 'Station',
                'type' => 'City Science & Technology Center',
                'color' => 'n/a',
                'others' => 'CSTC-ZCIC',
                'is_active' => 1,
            ],
            [
                'id' => 10,
                'name' => 'First Semester',
                'classification' => 'Period',
                'type' => 'Semester',
                'color' => 'n/a',
                'others' => '1-6',
                'is_active' => 1,
            ],
            [
                'id' => 11,
                'name' => 'Second Semester',
                'classification' => 'Period',
                'type' => 'Semester',
                'color' => 'n/a',
                'others' => '7-12',
                'is_active' => 1,
            ],
            [
                'id' => 12,
                'name' => 'First Quarter',
                'classification' => 'Period',
                'type' => 'Quarter',
                'color' => 'n/a',
                'others' => '1-3',
                'is_active' => 1,
            ],
            [
                'id' => 13,
                'name' => 'Second Quarter',
                'classification' => 'Period',
                'type' => 'Quarter',
                'color' => 'n/a',
                'others' => '4-6',
                'is_active' => 1,
            ],
            [
                'id' => 14,
                'name' => 'Third Quarter',
                'classification' => 'Period',
                'type' => 'Quarter',
                'color' => 'n/a',
                'others' => '7-9',
                'is_active' => 1,
            ],
            [
                'id' => 15,
                'name' => 'Fourth Quarter',
                'classification' => 'Period',
                'type' => 'Quarter',
                'color' => 'n/a',
                'others' => '10-12',
                'is_active' => 1,
            ],
            [
                'id' => 16,
                'name' => 'Within the Philippines',
                'classification' => 'Leave Details',
                'type' => 'Vacation Leave, Special Privilege Leave',
                'color' => 'n/a',
                'others' => 'specify',
                'is_active' => 1,
            ],
            [
                'id' => 17,
                'name' => 'Abroad',
                'classification' => 'Leave Details',
                'type' => 'Vacation Leave, Special Privilege Leave',
                'color' => 'n/a',
                'others' => 'specify ',
                'is_active' => 1,
            ],
            [
                'id' => 18,
                'name' => 'In Hospital',
                'classification' => 'Leave Details',
                'type' => 'Sick Leave',
                'color' => 'n/a',
                'others' => 'specify illness',
                'is_active' => 1,
            ],
            [
                'id' => 19,
                'name' => 'Out Patient',
                'classification' => 'Leave Details',
                'type' => 'Sick Leave',
                'color' => 'n/a',
                'others' => 'specify illness',
                'is_active' => 1,
            ],
            [
                'id' => 20,
                'name' => 'Completion of Master\'s Degree',
                'classification' => 'Leave Details',
                'type' => 'Study Leave',
                'color' => 'n/a',
                'others' => 'n/a',
                'is_active' => 1,
            ],
            [
                'id' => 21,
                'name' => 'BAR/Board Examination Review',
                'classification' => 'Leave Details',
                'type' => 'Study Leave',
                'color' => 'n/a',
                'others' => 'n/a',
                'is_active' => 1,
            ],
            [
                'id' => 22,
                'name' => 'Monetization of Leave Credits',
                'classification' => 'Leave Details',
                'type' => 'n/a',
                'color' => 'n/a',
                'others' => 'n/a',
                'is_active' => 1,
            ],
            [
                'id' => 23,
                'name' => 'Terminal Leave',
                'classification' => 'Leave Details',
                'type' => 'n/a',
                'color' => 'n/a',
                'others' => 'n/a',
                'is_active' => 1,
            ],
            [
                'id' => 24,
                'name' => 'Others',
                'classification' => 'Leave Details',
                'type' => 'n/a',
                'color' => 'n/a',
                'others' => 'n/a',
                'is_active' => 1,
            ]
        ]);
    }
}
