<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'username' => 'rij0311',
                'email' => 'kradjumli@gmail.com',
                'password' => '$2y$12$hRYvG.pV3jA2./LuSzHQ3Ob6A.ppwPz85Iddmss4Dw65lDdRrxEd2',
                'is_active' => 1,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => '2024-05-15 08:46:33',
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:45:47',
                'updated_at' => '2025-06-18 09:45:47',
            ),
            1 => 
            array (
                'id' => 2,
                'username' => 'rbg0110',
                'email' => 'ronnelg10@gmail.com',
                'password' => '$2y$12$unY55vD/hh79VrVU7VSe.OHLyhLEqFpdEsRKu4YEMSV4J7JFMHg6.',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:54',
                'updated_at' => '2025-06-18 09:46:54',
            ),
            2 => 
            array (
                'id' => 3,
                'username' => 'rss1204',
                'email' => 'rosemarie.salazar@gmail.com',
                'password' => '$2y$12$oTAaJd5LI/XW0PS2SarAKumXdo7nH49KngxBAUJZzVXC8ZUPL6N1u',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:55',
                'updated_at' => '2025-06-18 09:46:55',
            ),
            3 => 
            array (
                'id' => 4,
                'username' => 'slb0611',
                'email' => 'slbdost9zc@gmail.com',
                'password' => '$2y$12$ZVpNMVoIyYl/dWrGGSuSzum5EZMZ2DnHBWil/ewWfat0DuCUiKVLq',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:55',
                'updated_at' => '2025-06-18 09:46:55',
            ),
            4 => 
            array (
                'id' => 5,
                'username' => 'nta1119',
                'email' => 'protein63nt@gmail.com',
                'password' => '$2y$12$BVloH0skQjCUd7uR.fRnROSrjrALTMsjFrpdU939W8eFN.d.naLLG',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:55',
                'updated_at' => '2025-06-18 09:46:55',
            ),
            5 => 
            array (
                'id' => 6,
                'username' => 'rja0624',
                'email' => 'ricardo.apolinario@ro9.dost.gov.ph',
                'password' => '$2y$12$PsBRlS56JawHceFvd9tpZeukUk6ITT3R7Y6u3/EEzxnUy3Brsa.km',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:56',
                'updated_at' => '2025-06-18 09:46:56',
            ),
            6 => 
            array (
                'id' => 7,
                'username' => 'jto0418',
                'email' => 'janice.ong1214@gmail.com',
                'password' => '$2y$12$Xuxc/QGvBY.3CHudvqTIqurDKzpubZbORIGrICMMMEvSKlfRiUQpe',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:56',
                'updated_at' => '2025-06-18 09:46:56',
            ),
            7 => 
            array (
                'id' => 8,
                'username' => 'rml1005',
                'email' => 'rubenjr1005@gmail.com',
                'password' => '$2y$12$gVFkWzUo6UlwoB.5MTMoKeealw3pppRkA8Ob/dh33nrBQ34/o0psW',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:57',
                'updated_at' => '2025-06-18 09:46:57',
            ),
            8 => 
            array (
                'id' => 9,
                'username' => 'ses0118',
                'email' => 'suganobshadam@gmail.com',
                'password' => '$2y$12$g4ZCvmhntbwwyRQtbUahWeT0DEE0m/EFSSpthcZM2/Czz0.0U0zHa',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:57',
                'updated_at' => '2025-06-18 09:46:57',
            ),
            9 => 
            array (
                'id' => 10,
                'username' => 'mda0206',
                'email' => 'mdalivio2@gmail.com',
                'password' => '$2y$12$4ExBmkCaCZ4jwZ0mrnOR..LB8Tto2kWa0oeN32.ZiMaJ3fNUNnbtu',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:57',
                'updated_at' => '2025-06-18 09:46:57',
            ),
            10 => 
            array (
                'id' => 11,
                'username' => 'svm0828',
                'email' => 'shamudost9@gmail.com',
                'password' => '$2y$12$sY270XUD49JE6i97acZqeu2zv1BNmTwqB4A1fx5yf6r2a5/fBgm4i',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:58',
                'updated_at' => '2025-06-18 09:46:58',
            ),
            11 => 
            array (
                'id' => 12,
                'username' => 'ash0501',
                'email' => 'arleneherbieto@gmail.com',
                'password' => '$2y$12$XxBbgG9Yck/ZDSaH4W.wX.a/.rvSwfTjM/3S8EHH4tEvP1/XOZIO.',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:58',
                'updated_at' => '2025-06-18 09:46:58',
            ),
            12 => 
            array (
                'id' => 13,
                'username' => 'zfa0312',
                'email' => 'zorenantonio@gmail.com',
                'password' => '$2y$12$/YReyHLvLgJfL/uZEeZWpOUBljXAhLKXV2RpO6tTz6WtuVXhxxPN2',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:59',
                'updated_at' => '2025-06-18 09:46:59',
            ),
            13 => 
            array (
                'id' => 14,
                'username' => 'jjb1203',
                'email' => 'jali_badiola2005@yahoo.com',
                'password' => '$2y$12$GDiwN19fhHjdQq248lwqIe7CQJDX276oCUz4kO341PA.byPhJ/MrK',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:59',
                'updated_at' => '2025-06-18 09:46:59',
            ),
            14 => 
            array (
                'id' => 15,
                'username' => 'jbn0806',
                'email' => 'jpine652001@yahoo.com',
                'password' => '$2y$12$v07VKdx5PSFkHHJPOdYAC.VhOAeYsrn4/FkAU5H.zo9KbuZEbd.VO',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:46:59',
                'updated_at' => '2025-06-18 09:46:59',
            ),
            15 => 
            array (
                'id' => 16,
                'username' => 'ted0417',
                'email' => 'tediego@yahoo.com',
                'password' => '$2y$12$ctMoTKpPDvtuQJYMvbb6KuRW0mUI2HpGlTOFr.VZneR/Y.uaGGM7m',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:00',
                'updated_at' => '2025-06-18 09:47:00',
            ),
            16 => 
            array (
                'id' => 17,
                'username' => 'tmc0515',
                'email' => 'tmcatalya15@gmail.com',
                'password' => '$2y$12$2ICwTaTVQQT6XmqlsG/rauGgiBP.QO2cfnAzQEM/dm7Y6PvoVi.jW',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:00',
                'updated_at' => '2025-06-18 09:47:00',
            ),
            17 => 
            array (
                'id' => 18,
                'username' => 'ssb1121',
                'email' => 'bernardosheila21@gmail.com',
                'password' => '$2y$12$n3K1dC/jCYkFVWY3kyiYZOHzmtgpvxi/Dg69sNOrnb7sxpVQx6HHK',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:00',
                'updated_at' => '2025-06-18 09:47:00',
            ),
            18 => 
            array (
                'id' => 19,
                'username' => 'cbp1205',
                'email' => 'crisprieto05@gmail.com',
                'password' => '$2y$12$yc0dbopM95aTMFXES9jnw.6WUGUe/j3HBgHXjUn7EM6.YVJc0a2qS',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:01',
                'updated_at' => '2025-06-18 09:47:01',
            ),
            19 => 
            array (
                'id' => 20,
                'username' => 'jap0108',
                'email' => 'japidor@gmail.com',
                'password' => '$2y$12$kBrX4xnwxNVb7e1fQdWRa.OkJMiKMpscaroNynd9Hyj/FVgPDB0Oy',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:01',
                'updated_at' => '2025-06-18 09:47:01',
            ),
            20 => 
            array (
                'id' => 21,
                'username' => 'jdc0605',
                'email' => 'jhaykhaycee@gmail.com',
                'password' => '$2y$12$8qkYFtlNFJin2kI8pwNejONWidO/9TpbySi7n7AAuO7APZ8o2KaTC',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:01',
                'updated_at' => '2025-06-18 09:47:01',
            ),
            21 => 
            array (
                'id' => 22,
                'username' => 'clq1214',
                'email' => 'carlosyl_quinte@yahoo.com',
                'password' => '$2y$12$sX4FdqDalcKGvb30Oec3Xe3tgnB.drb7ENRczq0e4QEfS0dzVx3D.',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:02',
                'updated_at' => '2025-06-18 09:47:02',
            ),
            22 => 
            array (
                'id' => 23,
                'username' => 'jpa1101',
                'email' => 'jeyzel_aparri@yahoo.com',
                'password' => '$2y$12$umj.KvOk72lGMix983SENeHexVL93ebcy0CcgmcGZmBvp3K6356hy',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:02',
                'updated_at' => '2025-06-18 09:47:02',
            ),
            23 => 
            array (
                'id' => 24,
                'username' => 'nma0601',
                'email' => 'nuhman.aljani@gmail.com',
                'password' => '$2y$12$OYMqDZGc6BaZld7LAokjh.MABPWemZWNwb6gc6G7mYOOSZZDVY5ui',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:03',
                'updated_at' => '2025-06-18 09:47:03',
            ),
            24 => 
            array (
                'id' => 25,
                'username' => 'jtf0723',
                'email' => 'schezzo_july@yahoo.com',
                'password' => '$2y$12$dX8Sted32N8.vyKFmi/99ePvufRpoBOv/kG2Z8qTjAAP5s/.EhGc2',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:03',
                'updated_at' => '2025-06-18 09:47:03',
            ),
            25 => 
            array (
                'id' => 26,
                'username' => 'mcb0107',
                'email' => 'marilynannbueno@yahoo.com',
                'password' => '$2y$12$wHRZBAdnS5znZtVa1FFFVuFrIdjV0H98HvCMODUIdMFu80JSMOIeG',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:03',
                'updated_at' => '2025-06-18 09:47:03',
            ),
            26 => 
            array (
                'id' => 27,
                'username' => 'emm0715',
                'email' => 'enriquemmariano@gmail.com',
                'password' => '$2y$12$R7dgR77LrFcCXyUH.SGfrea05o4Ntdw4MRqJJLyAO78O01azmgMGe',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:04',
                'updated_at' => '2025-06-18 09:47:04',
            ),
            27 => 
            array (
                'id' => 28,
                'username' => 'sfj0919',
                'email' => 'jovenalsheryl@gmail.com',
                'password' => '$2y$12$PHllzrTgeW7tTnezmfQvOusM1bHYKjVSxXJXNO7KFq9LyEV50vT2q',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:04',
                'updated_at' => '2025-06-18 09:47:04',
            ),
            28 => 
            array (
                'id' => 29,
                'username' => 'gfp0608',
                'email' => 'pager578@gmail.com',
                'password' => '$2y$12$sQcVb79llP2Xt6eh3mYnUO.N/GjYCTLp57uN0ua6VVFs3UDbuXZ/i',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:05',
                'updated_at' => '2025-06-18 09:47:05',
            ),
            29 => 
            array (
                'id' => 30,
                'username' => 'ita0107',
                'email' => 'ingridtac.dostro09@yahoo.com',
                'password' => '$2y$12$HSEKOMYfFhaFjaNWY7vi0uZUFpulvOnRHL3Q0.quLhtECRe5.PooK',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:05',
                'updated_at' => '2025-06-18 16:09:30',
            ),
            30 => 
            array (
                'id' => 31,
                'username' => 'mgc0312',
                'email' => 'cachinmarc@yahoo.com',
                'password' => '$2y$12$XnoPktxISn3IN0EhXKYSLusmonklzP21Tz2Fy8x/JO2/9K83CM6ZO',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:05',
                'updated_at' => '2025-06-18 09:47:05',
            ),
            31 => 
            array (
                'id' => 32,
                'username' => 'crr0918',
                'email' => 'cc.rawr.07@gmail.com',
                'password' => '$2y$12$CSpMU8yf8204JcfA6uKC8eLwnHajiTBl6V5F9FEAco1gkKcBg4sNC',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:06',
                'updated_at' => '2025-06-18 09:47:06',
            ),
            32 => 
            array (
                'id' => 33,
                'username' => 'job0518',
                'email' => 'jelynobayonas@gmail.com',
                'password' => '$2y$12$5tyTGPRbqptFmhO98i6gX.4q4SjQfRfBowaHslnlzROknJCd.mYC6',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:06',
                'updated_at' => '2025-06-18 09:47:06',
            ),
            33 => 
            array (
                'id' => 34,
                'username' => 'krs0127',
                'email' => 'kristinemaesarita27@gmail.com',
                'password' => '$2y$12$AIo4HGvXE1jXYrxx2WxiBOBjfDQ6k3/SqDi92y4I5ERbxDB.LUhGy',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:07',
                'updated_at' => '2025-06-18 09:47:07',
            ),
            34 => 
            array (
                'id' => 35,
                'username' => 'mra1218',
                'email' => 'ninimarielleatilano@gmail.com',
                'password' => '$2y$12$sBd7PllGoA6Ok9eHFYK77.3KEGgdHjWq4ROSXE/JRrAOonS7vUxKm',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:07',
                'updated_at' => '2025-06-18 09:47:07',
            ),
            35 => 
            array (
                'id' => 36,
                'username' => 'mjbalina',
                'email' => 'markjayson181@yahoo.com',
                'password' => '$2y$12$r7bWFh0474KEoSNesNIv1OgVEJdu2CbxZqyxi1b8sy6VEz7jf0lvK',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:07',
                'updated_at' => '2025-06-18 09:47:07',
            ),
            36 => 
            array (
                'id' => 37,
                'username' => 'rrd0613',
                'email' => 'rrd0613@gmail.com',
                'password' => '$2y$12$v0/jOCVmLsDSPGIxVkO5Qufh04uJ8NqoIulyg2H.XvIA1ytPHHiRa',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:08',
                'updated_at' => '2025-06-18 09:47:08',
            ),
            37 => 
            array (
                'id' => 38,
                'username' => 'apl0318',
                'email' => 'apl@email.com',
                'password' => '$2y$12$LJzy3ltIkS4J9OVmmYwf/OibYMGXlAtQ.MRRANVUHx2pVCikdLhsS',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:08',
                'updated_at' => '2025-06-18 09:47:08',
            ),
            38 => 
            array (
                'id' => 39,
                'username' => 'cgb0323',
                'email' => 'calagodores2009@gmail.com',
                'password' => '$2y$12$30I5D.Q6Ub1cXFZd0kbRqeP1je0SuQw9LFg5lv1UE7NFI3Cx6HheC',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:09',
                'updated_at' => '2025-06-18 09:47:09',
            ),
            39 => 
            array (
                'id' => 40,
                'username' => 'krr1109',
                'email' => 'kevinkarlramosramiso@gmail.com',
                'password' => '$2y$12$N9116JjN4L5RqJybzsb6x.QFlMzieJih/nPVrFFp5WT5RyUH1MZqu',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:09',
                'updated_at' => '2025-06-18 09:47:09',
            ),
            40 => 
            array (
                'id' => 41,
                'username' => 'jbt0716',
                'email' => 'jayceetangon@gmail.com',
                'password' => '$2y$12$agx1DPos1Jvs4xeNs/fQaur6K6l1yafFYu47NItWSpXS7Ta0TfB6a',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:09',
                'updated_at' => '2025-06-18 09:47:09',
            ),
            41 => 
            array (
                'id' => 42,
                'username' => 'aaf0206',
                'email' => 'aaf0206@gmail.com',
                'password' => '$2y$12$soyjgwSvfQrBJiLLujV3ue2CKcxEwBRNRGxMBKEFSlBP.T3wsfjzO',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:10',
                'updated_at' => '2025-06-18 09:47:10',
            ),
            42 => 
            array (
                'id' => 43,
                'username' => 'als0205',
                'email' => 'analynsajiin@gmail.com',
                'password' => '$2y$12$jBuWUvxan9zR.0CqGErmYO4y4HWSIRUjChe/FmQx/cceimDvXJwoq',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:10',
                'updated_at' => '2025-06-18 09:47:10',
            ),
            43 => 
            array (
                'id' => 44,
                'username' => 'krc0108',
                'email' => 'kcarumba043@gmail.com',
                'password' => '$2y$12$7fs/ZKxb22O4/VCBTO9a4u3RNTENoQM10YQPGwOTkgQObuzb058iK',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:10',
                'updated_at' => '2025-06-18 09:47:10',
            ),
            44 => 
            array (
                'id' => 45,
                'username' => 'cmb0322',
                'email' => 'charisabaitit@gmail.com',
                'password' => '$2y$12$PuI/evkz7dvMPsCKhA8sy.N3vYIg0VEw2YhmbPNyC1h4KtKR5GCgq',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:11',
                'updated_at' => '2025-06-18 09:47:11',
            ),
            45 => 
            array (
                'id' => 46,
                'username' => 'jea1124',
                'email' => 'jealvarez.dost9@gmail.com',
                'password' => '$2y$12$2IisvJnP2NDDyzJtkjg0G.9./N5gNSz2ozcO6.OGCEX3R4Rk5FfW.',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:11',
                'updated_at' => '2025-06-18 09:47:11',
            ),
            46 => 
            array (
                'id' => 47,
                'username' => 'jdv0703',
                'email' => '123janmelvin@gmail.com',
                'password' => '$2y$12$kYk84cKBNvrDwvXvKorM5ermVXUmEuAwWhzRo8OL7XuvmToJBdama',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:12',
                'updated_at' => '2025-06-18 09:47:12',
            ),
            47 => 
            array (
                'id' => 48,
                'username' => 'aea0710',
                'email' => 'arman.aquino.35@gmail.com',
                'password' => '$2y$12$TqygMrL7kmz03oBQKo9yIuwBqy0/ugatEAqgVc9m/U68FS4FTgjiy',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:12',
                'updated_at' => '2025-06-18 09:47:12',
            ),
            48 => 
            array (
                'id' => 49,
                'username' => 'hsf0406',
                'email' => 'hersonfernando@gmail.com',
                'password' => '$2y$12$ljZkREzEbLC0kY93gfa8q.J48LnQesEpOvXzkiibZaXsSm/9OAWJS',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:13',
                'updated_at' => '2025-06-18 09:47:13',
            ),
            49 => 
            array (
                'id' => 50,
                'username' => 'ica0706',
                'email' => 'iancavenido@gmail.com',
                'password' => '$2y$12$PLIsREhTdhljic5lxIzA8etnkEOtrPYGJ6ZNQe0aiK3Dy09F4vZS2',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:13',
                'updated_at' => '2025-06-18 09:47:13',
            ),
            50 => 
            array (
                'id' => 51,
                'username' => 'dbc0220',
                'email' => 'dorzmacau12@gmail.com',
                'password' => '$2y$12$wpDiQ8f7e.MUwgf1zzNj2utuXF3fUC6qW3H075AmL6g1WvxWipS1q',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:13',
                'updated_at' => '2025-06-18 09:47:13',
            ),
            51 => 
            array (
                'id' => 52,
                'username' => 'jye0624',
                'email' => 'johnkenesmas@gmail.com',
                'password' => '$2y$12$iAOBgu4.U3yP7wsM3LZbEOqlzHVDQ9cyA2ukt9udADt/GWEA7oqYa',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:14',
                'updated_at' => '2025-06-18 09:47:14',
            ),
            52 => 
            array (
                'id' => 53,
                'username' => 'abs0530',
                'email' => 'aljeffrey.sardan30@gmail.com',
                'password' => '$2y$12$dXUeqgb2Q5U5VsF74/FR5.WXgMM8uLJrFIJAhRjufQquI8i244ytK',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:14',
                'updated_at' => '2025-06-18 09:47:14',
            ),
            53 => 
            array (
                'id' => 54,
                'username' => 'sva0308',
                'email' => 'stenelrizza@gmail.com',
                'password' => '$2y$12$tepob4CxZEVHR/tt7lGo4.r/Od26vL06YE8jMjQYTUGaF61YqU1lO',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:15',
                'updated_at' => '2025-06-18 09:47:15',
            ),
            54 => 
            array (
                'id' => 55,
                'username' => 'tbb1204',
                'email' => 'mystara.mballa@gmail.com',
                'password' => '$2y$12$5/hDiaZwgblnPIEJYjxpJOD6vFJQLTOQFqilKQnsa5oualLj97QJ2',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:15',
                'updated_at' => '2025-06-18 09:47:15',
            ),
            55 => 
            array (
                'id' => 56,
                'username' => 'eap1011',
                'email' => 'emaperdergat95@gmail.com',
                'password' => '$2y$12$0GcOeUdE1atmEqK.06aI8.yAK9fKiYO6YL1QER/xx1gAnHj5Jxo1C',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:15',
                'updated_at' => '2025-06-18 09:47:15',
            ),
            56 => 
            array (
                'id' => 57,
                'username' => 'hta0316',
                'email' => 'hermajoycea@gmail.com',
                'password' => '$2y$12$P.8hmbrgFyv8kua4za5XVOktGTE4FmxG4LGoP0piW45rAymj1itSS',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:16',
                'updated_at' => '2025-06-18 09:47:16',
            ),
            57 => 
            array (
                'id' => 58,
                'username' => 'jzd0318',
                'email' => 'jervesdalde93@gmail.com',
                'password' => '$2y$12$YPIUXaMbrDFSHeEcqO/5XepK.LrEjLTvdaQ8pDCxx.2Jnx.bBnU8i',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:16',
                'updated_at' => '2025-06-18 09:47:16',
            ),
            58 => 
            array (
                'id' => 59,
                'username' => 'dps0615',
                'email' => 'dreamlysumangil6@gmail.com',
                'password' => '$2y$12$1Oa7JpZ2XSI9vvZ9.mu5FeSLVwo/cveJV6osiDsbrVbPjQ6FuGnZi',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:17',
                'updated_at' => '2025-06-18 09:47:17',
            ),
            59 => 
            array (
                'id' => 60,
                'username' => 'dsb1118',
                'email' => 'dsb1118@gmail.com',
                'password' => '$2y$12$eFQ0hcu0zOwHSDyqMQTWQ./NNLe8jLO8XSm9rafprS5gNP3almDlG',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:17',
                'updated_at' => '2025-06-18 09:47:17',
            ),
            60 => 
            array (
                'id' => 61,
                'username' => 'bjt0414',
                'email' => 'bjt0414@gmail.com',
                'password' => '$2y$12$3X/4WUl2EESflSaG8hYw3u0tGS3gWU7Cr81dz4l.2EhUDOvhwVEWi',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:17',
                'updated_at' => '2025-06-18 09:47:17',
            ),
            61 => 
            array (
                'id' => 62,
                'username' => 'jba1006',
                'email' => 'joemar.anghag@gmail.com',
                'password' => '$2y$12$ZFV7e1SJtcyLHwLbT9SmwOrLhaOjR0N/HtcO4bk9BnaQzAVn0YBaO',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:18',
                'updated_at' => '2025-06-18 09:47:18',
            ),
            62 => 
            array (
                'id' => 63,
                'username' => 'jpf0611',
                'email' => 'joefryfernando@gmail.com',
                'password' => '$2y$12$UNhPyDSrWPw6ceucV2iZouJ8YgtqK7osXcQ8unINMB9Ej89jdF.xC',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:18',
                'updated_at' => '2025-06-18 09:47:18',
            ),
            63 => 
            array (
                'id' => 64,
                'username' => 'jbq0820',
                'email' => 'querubinjecilisaac@gmail.com',
                'password' => '$2y$12$Bo0af23bGxqxtuvNmx.cieCi3qKVCe/0gILZc3ATBjzy2tcEoXBw2',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:19',
                'updated_at' => '2025-06-18 09:47:19',
            ),
            64 => 
            array (
                'id' => 65,
                'username' => 'atp0610',
                'email' => 'patenzworld@gmail.com',
                'password' => '$2y$12$VGiaTezuJsCOEm5UvVtRPeICFCTFO5sJPQGNdYmNsXQ3ExnFXWBcy',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:19',
                'updated_at' => '2025-06-18 09:47:19',
            ),
            65 => 
            array (
                'id' => 66,
                'username' => 'mbb0704',
                'email' => 'marvin.basira@gmail.com',
                'password' => '$2y$12$ldLsTW48WRTA7.rSGErDUuC8sfEnO1lynH3HYIzDfXPuNUpqynV8a',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:19',
                'updated_at' => '2025-06-18 09:47:19',
            ),
            66 => 
            array (
                'id' => 67,
                'username' => 'aha0201',
                'email' => 'almafealbarico111@gmail.com',
                'password' => '$2y$12$sj3M/5kkkJZTf.tfuN0L8.crvWNWt28rOAKMpwkz6R.p0MW91Qmaa',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:20',
                'updated_at' => '2025-06-18 09:47:20',
            ),
            67 => 
            array (
                'id' => 68,
                'username' => 'mmh0824',
                'email' => 'mmh0824@gmail.com',
                'password' => '$2y$12$tynYnOLiCu0D31h5/38cOug9rr851uNg61yR4aBABHNHTqRD36T1G',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:20',
                'updated_at' => '2025-06-18 09:47:20',
            ),
            68 => 
            array (
                'id' => 69,
                'username' => 'csj0629',
                'email' => 'cindyjauculan@gmail.com',
                'password' => '$2y$12$lQdEVKWa.1sTxiXv7R3zIetGE8HKbN9gb0baHTiDnLmz/vOAawa6e',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:21',
                'updated_at' => '2025-06-18 09:47:21',
            ),
            69 => 
            array (
                'id' => 70,
                'username' => 'sbg0817',
                'email' => 'shiryllgarcia.1983@gmail.com',
                'password' => '$2y$12$OTBBZxLUgB7UE2lR834eWe3L3tFtfGbcKyQ3Dh/oQwMOxTjsLn3JW',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:21',
                'updated_at' => '2025-06-18 09:47:21',
            ),
            70 => 
            array (
                'id' => 71,
                'username' => 'rfg0225',
                'email' => 'davegramatica5@gmail.com',
                'password' => '$2y$12$jfS/C6/Ix8HFvEYkBy4MvOC5z.8TfWR46cy2jGHAK9r7r.2TuJDii',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:21',
                'updated_at' => '2025-06-18 09:47:21',
            ),
            71 => 
            array (
                'id' => 72,
                'username' => 'eav0505',
                'email' => 'evamaevilla@gmail.com',
                'password' => '$2y$12$2LHuxlSzoK/oOo6GjYOyJ.SvIQQWYxBTqDr6DPFNdTtQCwaHRYo7C',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:22',
                'updated_at' => '2025-06-18 09:47:22',
            ),
            72 => 
            array (
                'id' => 73,
                'username' => 'rcj1102',
                'email' => 'jruishnova@gmail.com',
                'password' => '$2y$12$oExWCMfCAwgELI58Oz9l0e.4U2hu6vqsgbP0pZotnq27NjppCDMEK',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:22',
                'updated_at' => '2025-06-18 09:47:22',
            ),
            73 => 
            array (
                'id' => 74,
                'username' => 'jtbalugo',
                'email' => 'jeffreybalugo@gmail.com',
                'password' => '$2y$12$Z4xrx4hCYi7UJG6MGRP74ef4blj4DkDFsqlzTEO1psNclK.vz6V5e',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:23',
                'updated_at' => '2025-06-18 09:47:23',
            ),
            74 => 
            array (
                'id' => 75,
                'username' => 'jol0917',
                'email' => 'josefkyle12345@gmail.com',
                'password' => '$2y$12$bpewsSP4iw9QXG/XpsKmqeYlsY7hbNQyCvyqwCNKhopfk6hc1Rvce',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:23',
                'updated_at' => '2025-06-18 09:47:23',
            ),
            75 => 
            array (
                'id' => 76,
                'username' => 'caz0306',
                'email' => 'zamorachristine09@gmail.com',
                'password' => '$2y$12$Uj9HlUIEe9EqihsmAVtWIe9tRHMvlfMOfDgOVAVDN4WKe4zmaMDfK',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:23',
                'updated_at' => '2025-06-18 09:47:23',
            ),
            76 => 
            array (
                'id' => 77,
                'username' => 'mac0905',
                'email' => 'miggyatilano@gmail.com',
                'password' => '$2y$12$nVZ1I7SDYyYxU0y/e0JEA.3B3jXX5SlSlr3ogDiMI4opbOHya2Bx6',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:24',
                'updated_at' => '2025-06-18 09:47:24',
            ),
            77 => 
            array (
                'id' => 78,
                'username' => 'pkg0326',
                'email' => 'kateegeerundio@gmail.com',
                'password' => '$2y$12$xP5duhV4jcefVGDczu4zveuRwa5OBCpy.3sLMcW7AnajqNUuWqzfa',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:24',
                'updated_at' => '2025-06-18 09:47:24',
            ),
            78 => 
            array (
                'id' => 79,
                'username' => 'jvp0315',
                'email' => 'jakesyrelpalma92@gmail.com',
                'password' => '$2y$12$MaO3hHwiS372pjIs8xmtVuJ8Pxvz0WdwoqGuAEpECXiEuRthLVECq',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:24',
                'updated_at' => '2025-06-18 09:47:24',
            ),
            79 => 
            array (
                'id' => 80,
                'username' => 'jae1204',
                'email' => 'jayaee02@gmail.com',
                'password' => '$2y$12$..ZMnNmOld0O/ab7nYev.e7EviDeKIWiBeQ8f.XL5fvWjQ0HWs4Zq',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:25',
                'updated_at' => '2025-06-18 09:47:25',
            ),
            80 => 
            array (
                'id' => 81,
                'username' => 'ece1204',
                'email' => 'empasemierose@gmail.com',
                'password' => '$2y$12$hT0FeoTgu0eQzV/UKs3PX.p6OHGk56.Q0d0fv7vmLKLvGbQ8U49Jm',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:25',
                'updated_at' => '2025-06-18 09:47:25',
            ),
            81 => 
            array (
                'id' => 82,
                'username' => 'scr1022',
                'email' => 'shielamariramos1@gmail.com',
                'password' => '$2y$12$xBNrKaUyCsFIJuUFIwjB4uuEmApylO7WLSVZXm/lkPavVDpWBcPEC',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:26',
                'updated_at' => '2025-06-18 09:47:26',
            ),
            82 => 
            array (
                'id' => 83,
                'username' => 'jer1231',
                'email' => 'jer1231@gmail.com',
                'password' => '$2y$12$1hY01XqMC9EichwE2/t.ieClPCPj2hu17M7NOf6unrMku2tPFRqT2',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:26',
                'updated_at' => '2025-06-18 09:47:26',
            ),
            83 => 
            array (
                'id' => 84,
                'username' => 'mmh0825',
                'email' => 'mmh0825@gmail.com',
                'password' => '$2y$12$fm5xL1s0XBPnvR0gXCkA0epc7f5gTYPpkoTMW5ssNs/0.VtkEyT3a',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:26',
                'updated_at' => '2025-06-18 09:47:26',
            ),
            84 => 
            array (
                'id' => 85,
                'username' => 'wpa0718',
                'email' => 'wpa0718@gmail.com',
                'password' => '$2y$12$gWBHL9ku6UvXKjMRO7fz5uyhYTMaN.l.dfv3zd5MeB0EAoJ86zMTO',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:27',
                'updated_at' => '2025-06-18 09:47:27',
            ),
            85 => 
            array (
                'id' => 86,
                'username' => 'acs0415',
                'email' => 'acs0415@gmail.com',
                'password' => '$2y$12$AsUM/DpztyQoyRQ6URIzwOl4Kra9UJOAoeE1iJyKBPxEqycVugN0y',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:27',
                'updated_at' => '2025-06-18 09:47:27',
            ),
            86 => 
            array (
                'id' => 87,
                'username' => 'gca1029',
                'email' => 'gca1029@gmail.com',
                'password' => '$2y$12$plcdP5EPOoTNQYpwElvcquP6hLjKcDLYND.mkeK1szzUcv6mLOt3C',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:27',
                'updated_at' => '2025-06-18 09:47:27',
            ),
            87 => 
            array (
                'id' => 88,
                'username' => 'bcc1009',
                'email' => 'beejaycarpio009@gmail.com',
                'password' => '$2y$12$ud3W2XT5GlTiCDtFWV.zS.VaSMxvNu961Eswybx3zb3ST5d6EWde6',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:28',
                'updated_at' => '2025-06-18 09:47:28',
            ),
            88 => 
            array (
                'id' => 89,
                'username' => 'fjh1202',
                'email' => 'wahidahimpon@gmail.com',
                'password' => '$2y$12$myE33Hmh2H5BBNe8gTLSje8e6MQue/Mfg4y2qsLHSJEWXPR6jqMHu',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:28',
                'updated_at' => '2025-06-18 09:47:28',
            ),
            89 => 
            array (
                'id' => 90,
                'username' => 'mmr0630',
                'email' => 'ellainerayman@gmail.com',
                'password' => '$2y$12$e5CNLLtdn8F5160pUnFE2OWLIDxapNlKt5KoziKhRWxML53ysJPcC',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:29',
                'updated_at' => '2025-06-18 09:47:29',
            ),
            90 => 
            array (
                'id' => 91,
                'username' => 'rbt0213',
                'email' => 'renieltumacas@gmail.com',
                'password' => '$2y$12$tbTPppMN9qMGlIV.SsRpBOy1b38aYsDG9A7u2J5BakFgts3KBph.y',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:29',
                'updated_at' => '2025-06-18 09:47:29',
            ),
            91 => 
            array (
                'id' => 92,
                'username' => 'acf1218',
                'email' => 'franciscoannamae18@gmail.com',
                'password' => '$2y$12$fh.MYCxdjx7mJSYLd2vCcOcwaTMRFvS.IW3vkzB6RAY8dVfFmbDBu',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:29',
                'updated_at' => '2025-06-18 09:47:29',
            ),
            92 => 
            array (
                'id' => 93,
                'username' => 'vyd1123',
                'email' => 'delossantosvanessa101@gmail.com',
                'password' => '$2y$12$KYyDYxI0e7z3JxFQYwaFku4INGbic6zOExOFNtrym9CxOafpA9d46',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:30',
                'updated_at' => '2025-06-18 09:47:30',
            ),
            93 => 
            array (
                'id' => 94,
                'username' => 'cch0826',
                'email' => 'halasanchav@gmail.com',
                'password' => '$2y$12$NUW4FBTHGVYXhqMBiNwjPuF0Ata9pnr99MClScaqlH1OMZeQOkwqq',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:30',
                'updated_at' => '2025-06-18 09:47:30',
            ),
            94 => 
            array (
                'id' => 95,
                'username' => 'mlc1029',
                'email' => 'mitzijeanettecudiera@gmail.com',
                'password' => '$2y$12$AqHuOyRdiaHXLDKFCZ93B.pfZwpoTkZXkJpRTkhAXLSVzGATaGSj.',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:30',
                'updated_at' => '2025-06-18 09:47:30',
            ),
            95 => 
            array (
                'id' => 96,
                'username' => 'gdm0728',
                'email' => 'manangangretchen@gmail.com',
                'password' => '$2y$12$QXXSjwumx7AiZjKBnTkSG.lviM4TzpYt7G1X/JBqY1aR9SeLTCDaO',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:31',
                'updated_at' => '2025-06-18 09:47:31',
            ),
            96 => 
            array (
                'id' => 97,
                'username' => 'rsg0519',
                'email' => 'rmgansan@gmail.com',
                'password' => '$2y$12$i.MWNDl/9./bDaoWx4.vpO32FgoQFUcWcDMFECGGOSurZWqUkj/UO',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:31',
                'updated_at' => '2025-06-18 09:47:31',
            ),
            97 => 
            array (
                'id' => 98,
                'username' => 'najada',
                'email' => 'najada@gmail.com',
                'password' => '$2y$12$9eglQpstCter4.6pHc3x9ueC3/3htXBBIxUlENajXoVQUSGVSrG1m',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:31',
                'updated_at' => '2025-06-18 09:47:31',
            ),
            98 => 
            array (
                'id' => 99,
                'username' => 'aat0428',
                'email' => 'angelicajoytubo@gmail.com',
                'password' => '$2y$12$qqwg7Ub75JUbz22SfQKEYunTVKw4TA2zRiuAujNra5EUbCx2zlmmG',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:32',
                'updated_at' => '2025-06-18 09:47:32',
            ),
            99 => 
            array (
                'id' => 100,
                'username' => 'mtu0104',
                'email' => 'marieferutal@gmail.com',
                'password' => '$2y$12$GBWWYzbK/RiePT5Bh9.X1O53r//Ux3DkPfxnIy7Df/14Bj7zMsKqC',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:32',
                'updated_at' => '2025-06-18 09:47:32',
            ),
            100 => 
            array (
                'id' => 101,
                'username' => 'aaa1129',
                'email' => 'aubrey.amparo@gmail.com',
                'password' => '$2y$12$yaTH.eKjcO4o97dZ5Lj6.OiVQelIweOQn6qkGGDm0mJbYjJxW7VGG',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:33',
                'updated_at' => '2025-06-18 09:47:33',
            ),
            101 => 
            array (
                'id' => 102,
                'username' => 'zsm0511',
                'email' => 'ayasaalimuyong@gmail.com',
                'password' => '$2y$12$87LHobYXOfH6eKieFHYzBOAbsBBvrqWAegxl5Dn0En961DTqcoCKi',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:33',
                'updated_at' => '2025-06-18 09:47:33',
            ),
            102 => 
            array (
                'id' => 103,
                'username' => 'ong0519',
                'email' => 'oniangelongomez@gmail.com',
                'password' => '$2y$12$7IsfYP5xwlEFvaNY.L8QbeISh3PxXDMzqnYRHyl5CdAYsw98uYNxG',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:33',
                'updated_at' => '2025-06-18 09:47:33',
            ),
            103 => 
            array (
                'id' => 104,
                'username' => 'cdc0610',
                'email' => 'camilchiong01@gmail.com',
                'password' => '$2y$12$uF.yupqr6QJ3Qz2Nb7lUJ.jCiUxNExtSb6XuV0Dy8l4ZnQB6b3BZC',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:34',
                'updated_at' => '2025-06-18 09:47:34',
            ),
            104 => 
            array (
                'id' => 105,
                'username' => 'ajg1125',
                'email' => 'adrianjudeg12@gmail.com',
                'password' => '$2y$12$3u5tJ03vsDWfTKhJUG4zWuDoNCeX.S6.3p5XZ1Odgc37Ludmaf7GW',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:34',
                'updated_at' => '2025-06-18 09:47:34',
            ),
            105 => 
            array (
                'id' => 106,
                'username' => 'jbs1015',
                'email' => 'sagutjulienneb@gmail.com',
                'password' => '$2y$12$jnFNIxYiq0sxP66Z.4OmbuPCrpv6q0tbigoCTy1/xgl.ysmzCwiLy',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:34',
                'updated_at' => '2025-06-18 09:47:34',
            ),
            106 => 
            array (
                'id' => 107,
                'username' => 'kga1129',
                'email' => 'gealonangelo97@gmail.com',
                'password' => '$2y$12$6YVDATwx/yGxp7NIhW9L9O7XALBw35skYtWWbXOqNTnTw9RvCd23u',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:35',
                'updated_at' => '2025-06-18 09:47:35',
            ),
            107 => 
            array (
                'id' => 108,
                'username' => 'jac1001',
                'email' => 'jccasquelo0100@gmail.com',
                'password' => '$2y$12$UruG71/Nees4sjm1lyS3U.Ca1V/gtihw8bfBBINHgXEuN4CuIKmVu',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:35',
                'updated_at' => '2025-06-18 09:47:35',
            ),
            108 => 
            array (
                'id' => 109,
                'username' => 'srs0305',
                'email' => 'sshervengeneil@gmail.com',
                'password' => '$2y$12$xROd5ZfN/gkBBUL4JZOo..3YEucJEQkLQO/4KaiBHzHF948GohXwu',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:36',
                'updated_at' => '2025-06-18 09:47:36',
            ),
            109 => 
            array (
                'id' => 110,
                'username' => 'rrc1002',
                'email' => 'rrc1002@gmail.com',
                'password' => '$2y$12$yVg2lzk818tHSvbz4eyFK..64fhSf1Iefb0TRXc.ycnMH4ohEvOQ6',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:36',
                'updated_at' => '2025-06-18 09:47:36',
            ),
            110 => 
            array (
                'id' => 111,
                'username' => 'imb0927',
                'email' => 'iolettebeatriz@gmail.com',
                'password' => '$2y$12$K6G2dpIE7SV3/kezZwoOoeN9WRfUbEQ8ix7tHd3w4HBR8y5yfb2hq',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:36',
                'updated_at' => '2025-06-18 09:47:36',
            ),
            111 => 
            array (
                'id' => 112,
                'username' => 'lma0414',
                'email' => 'anastacio.larra@gmail.com',
                'password' => '$2y$12$WY3lX.gF1gdyHRbg.nks5uz369VzuSYgmOBHADYtSBMAS3IRr9vOC',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:37',
                'updated_at' => '2025-06-18 09:47:37',
            ),
            112 => 
            array (
                'id' => 113,
                'username' => 'arn1020',
                'email' => 'ardleenatividad12@gmail.com',
                'password' => '$2y$12$SuqSv/abXWyT5ADab4J2ZOefwUp8dVSIUUsdgJLMmu.Ge5.xOLb.2',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:37',
                'updated_at' => '2025-06-18 09:47:37',
            ),
            113 => 
            array (
                'id' => 114,
                'username' => 'khb1124',
                'email' => 'brioneskenneth24@gmail.com',
                'password' => '$2y$12$eb7BUxOwRGWjBbdKMxkFU./FGoOKCrTeeTUW/XPtkynkFZtdJDjXa',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:37',
                'updated_at' => '2025-06-18 09:47:37',
            ),
            114 => 
            array (
                'id' => 115,
                'username' => 'aam0920',
                'email' => 'aigel.martinez1492@gmail.com',
                'password' => '$2y$12$m5iR14EdxC.FckVYn2xFxO1fGrfIHifSOoE2pFuR.oWkb2P2T8euu',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:38',
                'updated_at' => '2025-06-18 09:47:38',
            ),
            115 => 
            array (
                'id' => 116,
                'username' => 'rvr1202',
                'email' => 'rachelrubio@gmail.com',
                'password' => '$2y$12$otStdMas16GoyK7KX2yQq.PeMkj3..74u19NfT8z7t3qlEzrUwLYe',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:38',
                'updated_at' => '2025-06-18 09:47:38',
            ),
            116 => 
            array (
                'id' => 117,
                'username' => 'jbm1012',
                'email' => 'madarangjb@gmail.com',
                'password' => '$2y$12$s98Wfwflr2S1COKlV3ijhePwQeisfUapd6Mgn3NuvJNXecetpEdPO',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:39',
                'updated_at' => '2025-06-18 09:47:39',
            ),
            117 => 
            array (
                'id' => 118,
                'username' => 'njd0624',
                'email' => 'noelllanediaz73@gmail.com',
                'password' => '$2y$12$5sNwnkwz5.49lR1kF9lpzO1Mpz73C/0/OOyJfOyeq0oS3vdAN8c/G',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:39',
                'updated_at' => '2025-06-18 09:47:39',
            ),
            118 => 
            array (
                'id' => 119,
                'username' => 'arr0921',
                'email' => 'andreirabon@gmail.com',
                'password' => '$2y$12$.OejbU.EHFp8oiXeWGPYQegMvcjN.gVaio8k2X174ppu4Efe/rfhu',
                'is_active' => 0,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:47:39',
                'updated_at' => '2025-06-18 09:47:39',
            ),
            119 => 
            array (
                'id' => 120,
                'username' => 'dvs0707',
                'email' => 'danicamae614@gmail.com',
                'password' => '$2y$12$87jH4OxeQtvxoVQ0.t2.t.6Ss8V3mM08F1a9lhSUj6v/PkEE/ZJ82',
                'is_active' => 1,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 09:54:52',
                'updated_at' => '2025-06-18 09:54:52',
            ),
            120 => 
            array (
                'id' => 121,
                'username' => 'rra1114',
                'email' => 'rich@gmail.com',
                'password' => '$2y$12$45vPjEj9/xA2xu692TR4C.E1ke0jLjE2Q8wP92Zz7kpGgmXQe0Vfq',
                'is_active' => 1,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 10:35:17',
                'updated_at' => '2025-06-18 10:35:17',
            ),
            121 => 
            array (
                'id' => 122,
                'username' => 'rml0503',
                'email' => 'romeo@gmail.com',
                'password' => '$2y$12$u5ubOWDx4RRdHseNBE6UQeqv809wql4d1icWcmAbzfrXelRD6wCHm',
                'is_active' => 1,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 10:36:38',
                'updated_at' => '2025-06-18 10:36:38',
            ),
            122 => 
            array (
                'id' => 123,
                'username' => 'mre1014',
                'email' => 'melodrino60@gmail.com',
                'password' => '$2y$12$F9B5.B6Nu96i3XR14OsED.MebnB/y.0i0q9IPgTA8DJLspg5CRXiy',
                'is_active' => 1,
                'two_factor_secret' => NULL,
                'two_factor_recovery_codes' => NULL,
                'remember_token' => NULL,
                'email_verified_at' => NULL,
                'password_changed_at' => NULL,
                'two_factor_confirmed_at' => NULL,
                'created_at' => '2025-06-18 10:38:09',
                'updated_at' => '2025-06-18 10:38:09',
            ),
        ));

        
    }
}