<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserOrganizationsTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_organizations')->delete();
        
        \DB::table('user_organizations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 76,
                'division_id' => 4,
                'unit_id' => 15,
                'station_id' => 5,
                'user_id' => 1,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:45:52',
                'updated_at' => '2025-06-18 09:45:52',
            ),
            1 => 
            array (
                'id' => 2,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 81,
                'division_id' => 3,
                'unit_id' => 10,
                'station_id' => 5,
                'user_id' => 2,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:54',
                'updated_at' => '2025-06-18 17:10:22',
            ),
            2 => 
            array (
                'id' => 3,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 101,
                'division_id' => 2,
                'unit_id' => 2,
                'station_id' => 5,
                'user_id' => 3,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:55',
                'updated_at' => '2025-06-18 17:08:35',
            ),
            3 => 
            array (
                'id' => 4,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 61,
                'division_id' => 4,
                'unit_id' => 15,
                'station_id' => 5,
                'user_id' => 4,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:55',
                'updated_at' => '2025-06-18 16:51:37',
            ),
            4 => 
            array (
                'id' => 5,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 5,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:55',
                'updated_at' => '2025-06-18 09:46:55',
            ),
            5 => 
            array (
                'id' => 6,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 101,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 9,
                'user_id' => 6,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:56',
                'updated_at' => '2025-06-19 09:32:04',
            ),
            6 => 
            array (
                'id' => 7,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 47,
                'division_id' => 4,
                'unit_id' => 15,
                'station_id' => 5,
                'user_id' => 7,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:56',
                'updated_at' => '2025-06-18 17:04:45',
            ),
            7 => 
            array (
                'id' => 8,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 8,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:57',
                'updated_at' => '2025-06-18 09:46:57',
            ),
            8 => 
            array (
                'id' => 9,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 9,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:57',
                'updated_at' => '2025-06-18 09:46:57',
            ),
            9 => 
            array (
                'id' => 10,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 10,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:57',
                'updated_at' => '2025-06-18 09:46:57',
            ),
            10 => 
            array (
                'id' => 11,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 11,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:58',
                'updated_at' => '2025-06-18 09:46:58',
            ),
            11 => 
            array (
                'id' => 12,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 12,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:58',
                'updated_at' => '2025-06-18 09:46:58',
            ),
            12 => 
            array (
                'id' => 13,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 13,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:59',
                'updated_at' => '2025-06-18 09:46:59',
            ),
            13 => 
            array (
                'id' => 14,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 81,
                'division_id' => 3,
                'unit_id' => 9,
                'station_id' => 5,
                'user_id' => 14,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:59',
                'updated_at' => '2025-06-18 16:46:46',
            ),
            14 => 
            array (
                'id' => 15,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 39,
                'division_id' => 4,
                'unit_id' => 14,
                'station_id' => 5,
                'user_id' => 15,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:46:59',
                'updated_at' => '2025-06-18 17:01:02',
            ),
            15 => 
            array (
                'id' => 16,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 93,
                'division_id' => 2,
                'unit_id' => 5,
                'station_id' => 5,
                'user_id' => 16,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:00',
                'updated_at' => '2025-06-18 16:55:20',
            ),
            16 => 
            array (
                'id' => 17,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 81,
                'division_id' => 3,
                'unit_id' => 8,
                'station_id' => 5,
                'user_id' => 17,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:00',
                'updated_at' => '2025-06-18 16:54:47',
            ),
            17 => 
            array (
                'id' => 18,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 18,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:00',
                'updated_at' => '2025-06-18 09:47:00',
            ),
            18 => 
            array (
                'id' => 19,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 19,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:01',
                'updated_at' => '2025-06-18 09:47:01',
            ),
            19 => 
            array (
                'id' => 20,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 101,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 6,
                'user_id' => 20,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:01',
                'updated_at' => '2025-06-18 17:06:28',
            ),
            20 => 
            array (
                'id' => 21,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 93,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 6,
                'user_id' => 21,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:02',
                'updated_at' => '2025-06-18 16:52:27',
            ),
            21 => 
            array (
                'id' => 22,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 22,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:02',
                'updated_at' => '2025-06-18 09:47:02',
            ),
            22 => 
            array (
                'id' => 23,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 76,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 6,
                'user_id' => 23,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:02',
                'updated_at' => '2025-06-18 16:44:05',
            ),
            23 => 
            array (
                'id' => 24,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 101,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 7,
                'user_id' => 24,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:03',
                'updated_at' => '2025-06-18 16:43:41',
            ),
            24 => 
            array (
                'id' => 25,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 76,
                'division_id' => 4,
                'unit_id' => 15,
                'station_id' => 5,
                'user_id' => 25,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:03',
                'updated_at' => '2025-06-18 16:56:35',
            ),
            25 => 
            array (
                'id' => 26,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 26,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:03',
                'updated_at' => '2025-06-18 09:47:03',
            ),
            26 => 
            array (
                'id' => 27,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 27,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:04',
                'updated_at' => '2025-06-18 09:47:04',
            ),
            27 => 
            array (
                'id' => 28,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 28,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:04',
                'updated_at' => '2025-06-18 09:47:04',
            ),
            28 => 
            array (
                'id' => 29,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 101,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 8,
                'user_id' => 29,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:05',
                'updated_at' => '2025-06-18 17:05:52',
            ),
            29 => 
            array (
                'id' => 30,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 1,
                'division_id' => 3,
                'unit_id' => 7,
                'station_id' => 5,
                'user_id' => 30,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:05',
                'updated_at' => '2025-06-18 16:24:33',
            ),
            30 => 
            array (
                'id' => 31,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 93,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 7,
                'user_id' => 31,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:05',
                'updated_at' => '2025-06-18 16:53:07',
            ),
            31 => 
            array (
                'id' => 32,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 93,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 8,
                'user_id' => 32,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:06',
                'updated_at' => '2025-06-18 17:07:44',
            ),
            32 => 
            array (
                'id' => 33,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 76,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 7,
                'user_id' => 33,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:06',
                'updated_at' => '2025-06-18 16:50:52',
            ),
            33 => 
            array (
                'id' => 34,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 76,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 8,
                'user_id' => 34,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:07',
                'updated_at' => '2025-06-18 17:09:16',
            ),
            34 => 
            array (
                'id' => 35,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 35,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:07',
                'updated_at' => '2025-06-18 09:47:07',
            ),
            35 => 
            array (
                'id' => 36,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 61,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 7,
                'user_id' => 36,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:07',
                'updated_at' => '2025-06-18 16:50:11',
            ),
            36 => 
            array (
                'id' => 37,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 37,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:08',
                'updated_at' => '2025-06-18 09:47:08',
            ),
            37 => 
            array (
                'id' => 38,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 21,
                'division_id' => 2,
                'unit_id' => 2,
                'station_id' => 5,
                'user_id' => 38,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:08',
                'updated_at' => '2025-06-18 16:58:02',
            ),
            38 => 
            array (
                'id' => 39,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 39,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:09',
                'updated_at' => '2025-06-18 09:47:09',
            ),
            39 => 
            array (
                'id' => 40,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 40,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:09',
                'updated_at' => '2025-06-18 09:47:09',
            ),
            40 => 
            array (
                'id' => 41,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 41,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:09',
                'updated_at' => '2025-06-18 09:47:09',
            ),
            41 => 
            array (
                'id' => 42,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 42,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:10',
                'updated_at' => '2025-06-18 09:47:10',
            ),
            42 => 
            array (
                'id' => 43,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 43,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:10',
                'updated_at' => '2025-06-18 09:47:10',
            ),
            43 => 
            array (
                'id' => 44,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 61,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 6,
                'user_id' => 44,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:10',
                'updated_at' => '2025-06-18 16:53:57',
            ),
            44 => 
            array (
                'id' => 45,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 45,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:11',
                'updated_at' => '2025-06-18 09:47:11',
            ),
            45 => 
            array (
                'id' => 46,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 46,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:11',
                'updated_at' => '2025-06-18 09:47:11',
            ),
            46 => 
            array (
                'id' => 47,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 47,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:12',
                'updated_at' => '2025-06-18 09:47:12',
            ),
            47 => 
            array (
                'id' => 48,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 48,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:12',
                'updated_at' => '2025-06-18 09:47:12',
            ),
            48 => 
            array (
                'id' => 49,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 49,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:13',
                'updated_at' => '2025-06-18 09:47:13',
            ),
            49 => 
            array (
                'id' => 50,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 50,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:13',
                'updated_at' => '2025-06-18 09:47:13',
            ),
            50 => 
            array (
                'id' => 51,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 47,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 6,
                'user_id' => 51,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:14',
                'updated_at' => '2025-06-18 16:57:13',
            ),
            51 => 
            array (
                'id' => 52,
                'status_id' => 2,
                'type_id' => 15,
                'position_id' => 61,
                'division_id' => 4,
                'unit_id' => 18,
                'station_id' => 6,
                'user_id' => 52,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:14',
                'updated_at' => '2025-06-18 16:55:54',
            ),
            52 => 
            array (
                'id' => 53,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 53,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:14',
                'updated_at' => '2025-06-18 09:47:14',
            ),
            53 => 
            array (
                'id' => 54,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 54,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:15',
                'updated_at' => '2025-06-18 09:47:15',
            ),
            54 => 
            array (
                'id' => 55,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 55,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:15',
                'updated_at' => '2025-06-18 09:47:15',
            ),
            55 => 
            array (
                'id' => 56,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 56,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:15',
                'updated_at' => '2025-06-18 09:47:15',
            ),
            56 => 
            array (
                'id' => 57,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 57,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:16',
                'updated_at' => '2025-06-18 09:47:16',
            ),
            57 => 
            array (
                'id' => 58,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 58,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:16',
                'updated_at' => '2025-06-18 09:47:16',
            ),
            58 => 
            array (
                'id' => 59,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 59,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:17',
                'updated_at' => '2025-06-18 09:47:17',
            ),
            59 => 
            array (
                'id' => 60,
                'status_id' => 2,
                'type_id' => 17,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 60,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:17',
                'updated_at' => '2025-06-18 09:47:17',
            ),
            60 => 
            array (
                'id' => 61,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 61,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:17',
                'updated_at' => '2025-06-18 09:47:17',
            ),
            61 => 
            array (
                'id' => 62,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 62,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:18',
                'updated_at' => '2025-06-18 09:47:18',
            ),
            62 => 
            array (
                'id' => 63,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 63,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:18',
                'updated_at' => '2025-06-18 09:47:18',
            ),
            63 => 
            array (
                'id' => 64,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 64,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:19',
                'updated_at' => '2025-06-18 09:47:19',
            ),
            64 => 
            array (
                'id' => 65,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 65,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:19',
                'updated_at' => '2025-06-18 09:47:19',
            ),
            65 => 
            array (
                'id' => 66,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 66,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:19',
                'updated_at' => '2025-06-18 09:47:19',
            ),
            66 => 
            array (
                'id' => 67,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 67,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:20',
                'updated_at' => '2025-06-18 09:47:20',
            ),
            67 => 
            array (
                'id' => 68,
                'status_id' => 2,
                'type_id' => 17,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 68,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:20',
                'updated_at' => '2025-06-18 09:47:20',
            ),
            68 => 
            array (
                'id' => 69,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 69,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:21',
                'updated_at' => '2025-06-18 09:47:21',
            ),
            69 => 
            array (
                'id' => 70,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 70,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:21',
                'updated_at' => '2025-06-18 09:47:21',
            ),
            70 => 
            array (
                'id' => 71,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 71,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:21',
                'updated_at' => '2025-06-18 09:47:21',
            ),
            71 => 
            array (
                'id' => 72,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 72,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:22',
                'updated_at' => '2025-06-18 09:47:22',
            ),
            72 => 
            array (
                'id' => 73,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 73,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:22',
                'updated_at' => '2025-06-18 09:47:22',
            ),
            73 => 
            array (
                'id' => 74,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 74,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:23',
                'updated_at' => '2025-06-18 09:47:23',
            ),
            74 => 
            array (
                'id' => 75,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 75,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:23',
                'updated_at' => '2025-06-18 09:47:23',
            ),
            75 => 
            array (
                'id' => 76,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 76,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:23',
                'updated_at' => '2025-06-18 09:47:23',
            ),
            76 => 
            array (
                'id' => 77,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 77,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:24',
                'updated_at' => '2025-06-18 09:47:24',
            ),
            77 => 
            array (
                'id' => 78,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 78,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:24',
                'updated_at' => '2025-06-18 09:47:24',
            ),
            78 => 
            array (
                'id' => 79,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 79,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:24',
                'updated_at' => '2025-06-18 09:47:24',
            ),
            79 => 
            array (
                'id' => 80,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 80,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:25',
                'updated_at' => '2025-06-18 09:47:25',
            ),
            80 => 
            array (
                'id' => 81,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 81,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:25',
                'updated_at' => '2025-06-18 09:47:25',
            ),
            81 => 
            array (
                'id' => 82,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 82,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:26',
                'updated_at' => '2025-06-18 09:47:26',
            ),
            82 => 
            array (
                'id' => 83,
                'status_id' => 2,
                'type_id' => 17,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 83,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:26',
                'updated_at' => '2025-06-18 09:47:26',
            ),
            83 => 
            array (
                'id' => 84,
                'status_id' => 2,
                'type_id' => 17,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 84,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:26',
                'updated_at' => '2025-06-18 09:47:26',
            ),
            84 => 
            array (
                'id' => 85,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 85,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:27',
                'updated_at' => '2025-06-18 09:47:27',
            ),
            85 => 
            array (
                'id' => 86,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 86,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:27',
                'updated_at' => '2025-06-18 09:47:27',
            ),
            86 => 
            array (
                'id' => 87,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 87,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:28',
                'updated_at' => '2025-06-18 09:47:28',
            ),
            87 => 
            array (
                'id' => 88,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 88,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:28',
                'updated_at' => '2025-06-18 09:47:28',
            ),
            88 => 
            array (
                'id' => 89,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 89,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:28',
                'updated_at' => '2025-06-18 09:47:28',
            ),
            89 => 
            array (
                'id' => 90,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 90,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:29',
                'updated_at' => '2025-06-18 09:47:29',
            ),
            90 => 
            array (
                'id' => 91,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 91,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:29',
                'updated_at' => '2025-06-18 09:47:29',
            ),
            91 => 
            array (
                'id' => 92,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 92,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:29',
                'updated_at' => '2025-06-18 09:47:29',
            ),
            92 => 
            array (
                'id' => 93,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 93,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:30',
                'updated_at' => '2025-06-18 09:47:30',
            ),
            93 => 
            array (
                'id' => 94,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 94,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:30',
                'updated_at' => '2025-06-18 09:47:30',
            ),
            94 => 
            array (
                'id' => 95,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 95,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:30',
                'updated_at' => '2025-06-18 09:47:30',
            ),
            95 => 
            array (
                'id' => 96,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 96,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:31',
                'updated_at' => '2025-06-18 09:47:31',
            ),
            96 => 
            array (
                'id' => 97,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 97,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:31',
                'updated_at' => '2025-06-18 09:47:31',
            ),
            97 => 
            array (
                'id' => 98,
                'status_id' => 2,
                'type_id' => 17,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 98,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:31',
                'updated_at' => '2025-06-18 09:47:31',
            ),
            98 => 
            array (
                'id' => 99,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 99,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:32',
                'updated_at' => '2025-06-18 09:47:32',
            ),
            99 => 
            array (
                'id' => 100,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 100,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:32',
                'updated_at' => '2025-06-18 09:47:32',
            ),
            100 => 
            array (
                'id' => 101,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 101,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:33',
                'updated_at' => '2025-06-18 09:47:33',
            ),
            101 => 
            array (
                'id' => 102,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 102,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:33',
                'updated_at' => '2025-06-18 09:47:33',
            ),
            102 => 
            array (
                'id' => 103,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 103,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:33',
                'updated_at' => '2025-06-18 09:47:33',
            ),
            103 => 
            array (
                'id' => 104,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 104,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:34',
                'updated_at' => '2025-06-18 09:47:34',
            ),
            104 => 
            array (
                'id' => 105,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 105,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:34',
                'updated_at' => '2025-06-18 09:47:34',
            ),
            105 => 
            array (
                'id' => 106,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 106,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:35',
                'updated_at' => '2025-06-18 09:47:35',
            ),
            106 => 
            array (
                'id' => 107,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 107,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:35',
                'updated_at' => '2025-06-18 09:47:35',
            ),
            107 => 
            array (
                'id' => 108,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 108,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:35',
                'updated_at' => '2025-06-18 09:47:35',
            ),
            108 => 
            array (
                'id' => 109,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 109,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:36',
                'updated_at' => '2025-06-18 09:47:36',
            ),
            109 => 
            array (
                'id' => 110,
                'status_id' => 2,
                'type_id' => 17,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 110,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:36',
                'updated_at' => '2025-06-18 09:47:36',
            ),
            110 => 
            array (
                'id' => 111,
                'status_id' => 2,
                'type_id' => 17,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 111,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:36',
                'updated_at' => '2025-06-18 09:47:36',
            ),
            111 => 
            array (
                'id' => 112,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 112,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:37',
                'updated_at' => '2025-06-18 09:47:37',
            ),
            112 => 
            array (
                'id' => 113,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 113,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:37',
                'updated_at' => '2025-06-18 09:47:37',
            ),
            113 => 
            array (
                'id' => 114,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 114,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:37',
                'updated_at' => '2025-06-18 09:47:37',
            ),
            114 => 
            array (
                'id' => 115,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 115,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:38',
                'updated_at' => '2025-06-18 09:47:38',
            ),
            115 => 
            array (
                'id' => 116,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 116,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:38',
                'updated_at' => '2025-06-18 09:47:38',
            ),
            116 => 
            array (
                'id' => 117,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 117,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:39',
                'updated_at' => '2025-06-18 09:47:39',
            ),
            117 => 
            array (
                'id' => 118,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 118,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:39',
                'updated_at' => '2025-06-18 09:47:39',
            ),
            118 => 
            array (
                'id' => 119,
                'status_id' => 2,
                'type_id' => 16,
                'position_id' => 1,
                'division_id' => 1,
                'unit_id' => 1,
                'station_id' => 1,
                'user_id' => 119,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:47:39',
                'updated_at' => '2025-06-18 09:47:39',
            ),
            119 => 
            array (
                'id' => 120,
                'status_id' => 1,
                'type_id' => 16,
                'position_id' => 75,
                'division_id' => 4,
                'unit_id' => 15,
                'station_id' => 5,
                'user_id' => 120,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 09:54:52',
                'updated_at' => '2025-06-18 09:54:52',
            ),
            120 => 
            array (
                'id' => 121,
                'status_id' => 1,
                'type_id' => 340,
                'position_id' => 110,
                'division_id' => 35,
                'unit_id' => 19,
                'station_id' => 5,
                'user_id' => 121,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 10:35:17',
                'updated_at' => '2025-06-18 10:35:17',
            ),
            121 => 
            array (
                'id' => 122,
                'status_id' => 1,
                'type_id' => 340,
                'position_id' => 110,
                'division_id' => 35,
                'unit_id' => 19,
                'station_id' => 5,
                'user_id' => 122,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 10:36:38',
                'updated_at' => '2025-06-18 10:36:38',
            ),
            122 => 
            array (
                'id' => 123,
                'status_id' => 1,
                'type_id' => 340,
                'position_id' => 110,
                'division_id' => 35,
                'unit_id' => 19,
                'station_id' => 5,
                'user_id' => 123,
                'start_at' => NULL,
                'end_at' => NULL,
                'created_at' => '2025-06-18 10:38:09',
                'updated_at' => '2025-06-18 10:38:09',
            ),
        ));

        
    }
}