<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserInformationTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_information')->delete();
        
        \DB::table('user_information')->insert(array (
            0 => 
            array (
                'id' => 1,
                'accounts' => 'eyJpdiI6IkQyeXhHdU01NGFMSVgzS1JhOG43YlE9PSIsInZhbHVlIjoiVkhTa0VjNEFiNTUwOUN2ME9ZMEYvVHUvUFJpZHN6dDZwekhaakd5SXYyUzA2NTNoai9GQklaNkdGdllhbDZzR085bG5iSk0xaW85RVFQRk1RRmNoVVI2QzNkRHU3VzNLZ1ZsKzdKejliNXRtS3d2eWcvRDhHWWhyUjZGSXFJUlZMdk10TlduTGhWSVdaQWE0eFVqcXNDMTF2MlhCV29GK1V3WVEzZis2b3JQRWJzTExza1h6ZUFkb2ZsSzNLejdTOGlObTlxbzQyVURUK0RyZXVScFVSTVlhOFhjVjhrdEpuUWR5bFhHSnE5TGpSczRPa1RyZ09lODR4MXRIQ3ZRK3dycm9hdWJVWXluTEd2MVFGZTFmN3JHQ3ovYW1ZZkNsTHdYaTZ3K0FvNEdSSWxpalQwdjhuTDAybWczeFd5azk5bTFINjNNYXRtQnlReisrNC9oeXhYendEMGd2cXNnWnZhR0gxM2VzTzFPQVhaTkp4NGhTNXluczJ3VlVDcTg2OGNCV0Jodzg3YzllM1IzOVluUnZvaW84OENpZVhjdkM2VEgxNG95ODlSNVp3SG9BUFdGK3NXU1RjQ2xBWnRVa1M2MXNYMVRWWW1rYjl5aEo3dVg4VGZrV1h5bFhPQjgvR2hxa0hSWGxTQ0J1TGorSkJ2UkYwR2RtYk5tTWhLVlArRnBUVTFtNldDTzk0NTQ3MjdaSFZ2b08vSVpJVU1tUWttVzAyVjNyL0VLSnNJNUNSSmk0ZWRiZ0ZHR0dJem5oUk9BN0JpYzBGRlkrdGc0aWZLQUhEd2FKcCtpTWNqTGwxcHVYQXlyRlRHMXR1dmp2Y1RoeUF5VHFUNVhNS0RmV1hNQlZFYW1TVHQrMFdIeW9iYlY4UWU1Z0ZQMFlCekZnbSs5cENtdTk2Nmc9IiwibWFjIjoiZDdlYTMwMjRlZWY4OTc5OTBhZDc2ZTBjYTMxZGE1NGVmNjMxYzczYTljMzE5ODgxMjI4OTgzMjM0ZmQ2YTYyZSIsInRhZyI6IiJ9',
                'contacts' => 'eyJpdiI6ImNqTGlzT1d4UFpOS3hHcUNaLysyN2c9PSIsInZhbHVlIjoibGpzZnkzZzhBRGwvT0oyMTY2ejZnWkhBTGlPYXg4YTRjOXd5WVU3TmxaaWx6OTc4S3FFbnFxL1pMaUtQMHBlOU5QRFVZRXFyL25QVWVvYk9FdHBabGxPVnRBRElnV1FrV2ZZUllqd1RYeGJWV2EvdWFWMVE5dFRRQjlQU2FERzl0YlZPVnJmY0FkSnJzOFlISFRJTXR6eFI2S096YlFZOVJReDNhcEpNVkRxM2g5NTRmQjN3QnFsb2FUcFdaMUsrSGdBa0xhTmdoZFdubmYzeEpqTDJ3ZnA2VzZvaHBVOTc5VEZOREFDandrREZlazNydXI1YWhtMit2YzhsMDZuU0cweXVLYXhiRlFoa01OeHlQeHF0TXNoTFNiSmV3UVdPUFF0eFJVbC9OeUlWYU5WR05PTjFOYW5iamZ4aUVnUEZPWGFrT1Y5TkZQM3gybCt5R2ViTVFubzFpNVRuWmszL1RsQ2graU1uNEVFRFI0aGR6OFJBWDZrQVpSdEcyTnhEeTM5N1J2dloreGtJOGVQQUhUTHEvVUpDZEdaUFlDT3pEOTZ4VmlpbEdTSElqeldoQlArT2RrWGRJdEJ0UTAwUXBVdXlTcnpJcFNDSllmWjNMZ2lncmZwK0tsVy9jZUcvWlhVZDkxQm9rdHhlbVF5VGxkdGNOYnUzMUpzMmI2UUZTVTVHWU8ybldLTnlRTkptZkNHMDk3RVR6QVV0U3VXckNQQTJ4WE9NQjlPV1F0Wm1vMTdvNEZ0Qk5LNWVUcTRhckdENjZlaGQzU21LdFN0d2Y5WUhCQT09IiwibWFjIjoiYTExNDg1NWUxZmQ5OTkzYjBkNDg5YjgxMmM0YmFlMTcxMmYzZmFmNzllNWE5YjY3ZmZlZDU5MTJlZTI0MThlMCIsInRhZyI6IiJ9',
                'backgrounds' => 'eyJpdiI6ImhEb3FjZ0JmazBYdExEa0prQmJIT2c9PSIsInZhbHVlIjoiWEhBNVJobzg1Zm01SGVGckkwVFNDazVEZTF5NmhRWkNSdVRiN3FpUERmVVcrQ3RDcEdYRlpnUXYrK2pycVdzQnpPeVhlU0JPWCtKS1F5eEtUSXdkM1FSYzd1QmdWZEJRdDZJRnVabjJLUFJpenFVbWw4SDdEdmpuNnR6MHZoZ2FJWngxbjJJeFpuc2FSOGhKS1FGcEdxN1d5M1hjQkhEMkhGTnZVRnAzUExEaytROU1Fem8raTg1bkppYWtEekF6K2U2WTRDaHBOVkRkbWFFOE15d2dOeExYKytLb0VyL3Q0eWFrMmgyUUpEZHFMU1dTWFRodFBXMmUyakxVdVVEdE9XdGZySFM2anhoWWJvSjBPaTZkcHRxTDVWb1JHMTFKMkpCU1IwVks3RmM9IiwibWFjIjoiM2EzOTYxYmIyOTE5ZWMzNDg3YmRlMzhmODRiNzRmNDc4MGVmMDVkODk3YTRhMThjMDc2MTQxMzQzMTM1MDA2NiIsInRhZyI6IiJ9',
                'user_id' => 1,
                'created_at' => '2025-02-24 12:36:06',
                'updated_at' => '2025-02-24 12:36:06',
            ),
        ));

        
    }
}