<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UserProfilesTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('user_profiles')->delete();
        
        \DB::table('user_profiles')->insert(array (
            0 => 
            array (
                'id' => 1,
                'firstname' => 'Ra-ouf',
                'lastname' => 'Jumli',
                'middlename' => 'Indanan',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '1994-03-11',
                'contact_no' => '09171531652',
                'avatar' => 'avatar.jpg',
                'signature' => NULL,
                'marital_id' => 3,
                'religion_id' => 20,
                'blood_id' => 7,
                'user_id' => 1,
                'created_at' => '2025-06-18 09:45:47',
                'updated_at' => '2025-06-20 09:22:52',
            ),
            1 => 
            array (
                'id' => 2,
                'firstname' => 'Ronnel',
                'lastname' => 'Gundoy',
                'middlename' => 'Baluan',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123454312',
                'avatar' => 'rbg0110.jpg',
                'signature' => 'rbg0110.png',
                'marital_id' => 3,
                'religion_id' => 20,
                'blood_id' => 7,
                'user_id' => 2,
                'created_at' => '2025-06-18 09:46:54',
                'updated_at' => '2025-06-20 09:23:25',
            ),
            2 => 
            array (
                'id' => 3,
                'firstname' => 'Rosemarie',
                'lastname' => 'Salazar',
                'middlename' => 'Sinsuan',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123450000',
                'avatar' => 'rss1204.jpg',
                'signature' => 'rss1204.png',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 3,
                'created_at' => '2025-06-18 09:46:55',
                'updated_at' => '2025-06-18 17:08:35',
            ),
            3 => 
            array (
                'id' => 4,
                'firstname' => 'Sonora',
                'lastname' => 'Buñag',
                'middlename' => 'Leonora',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456766',
                'avatar' => 'slb0611.jpg',
                'signature' => 'slb0611.png',
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 4,
                'created_at' => '2025-06-18 09:46:55',
                'updated_at' => '2025-06-18 16:51:37',
            ),
            4 => 
            array (
                'id' => 5,
                'firstname' => 'Noel',
                'lastname' => 'Arquiza',
                'middlename' => 'Toh',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'nta1119.jpg',
                'signature' => 'nta1119.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 5,
                'created_at' => '2025-06-18 09:46:55',
                'updated_at' => '2025-06-18 09:46:55',
            ),
            5 => 
            array (
                'id' => 6,
                'firstname' => 'Ricardo Iii',
                'lastname' => 'Apolinario',
                'middlename' => 'Jaldon',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456788',
                'avatar' => 'rja0624.jpg',
                'signature' => 'rja0624.png',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 6,
                'created_at' => '2025-06-18 09:46:56',
                'updated_at' => '2025-06-18 16:39:49',
            ),
            6 => 
            array (
                'id' => 7,
                'firstname' => 'Janice',
                'lastname' => 'Ong',
                'middlename' => 'Tangcalagan',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456098',
                'avatar' => 'jto0418.jpg',
                'signature' => 'jto0418.png',
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 7,
                'created_at' => '2025-06-18 09:46:56',
                'updated_at' => '2025-06-18 17:04:45',
            ),
            7 => 
            array (
                'id' => 8,
                'firstname' => 'Ruben Jr',
                'lastname' => 'Lim',
                'middlename' => 'Matchon',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'rml1005.jpg',
                'signature' => 'rml1005.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 8,
                'created_at' => '2025-06-18 09:46:57',
                'updated_at' => '2025-06-18 09:46:57',
            ),
            8 => 
            array (
                'id' => 9,
                'firstname' => 'Shadam',
                'lastname' => 'Suganob',
                'middlename' => 'Eroy',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'ses0118.jpg',
                'signature' => 'ses0118.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 9,
                'created_at' => '2025-06-18 09:46:57',
                'updated_at' => '2025-06-18 09:46:57',
            ),
            9 => 
            array (
                'id' => 10,
                'firstname' => 'Merly',
                'lastname' => 'Alivio',
                'middlename' => 'Dalinsog',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'mda0206.jpg',
                'signature' => 'mda0206.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 10,
                'created_at' => '2025-06-18 09:46:57',
                'updated_at' => '2025-06-18 09:46:57',
            ),
            10 => 
            array (
                'id' => 11,
                'firstname' => 'Sharmaine',
                'lastname' => 'Morales',
                'middlename' => 'Villagracia',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'svm0828.jpg',
                'signature' => 'svm0828.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 11,
                'created_at' => '2025-06-18 09:46:58',
                'updated_at' => '2025-06-18 09:46:58',
            ),
            11 => 
            array (
                'id' => 12,
                'firstname' => 'Arlene',
                'lastname' => 'Herbieto',
                'middlename' => 'Sabalde',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'ash0501.jpg',
                'signature' => 'ash0501.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 12,
                'created_at' => '2025-06-18 09:46:58',
                'updated_at' => '2025-06-18 09:46:58',
            ),
            12 => 
            array (
                'id' => 13,
                'firstname' => 'Zoren',
                'lastname' => 'Antonio',
                'middlename' => 'Fabile',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'zfa0312.jpg',
                'signature' => 'zfa0312.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 13,
                'created_at' => '2025-06-18 09:46:59',
                'updated_at' => '2025-06-18 09:46:59',
            ),
            13 => 
            array (
                'id' => 14,
                'firstname' => 'Jali',
                'lastname' => 'Badiola',
                'middlename' => 'Jamandre',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456711',
                'avatar' => 'jjb1203.jpg',
                'signature' => 'jjb1203.png',
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 14,
                'created_at' => '2025-06-18 09:46:59',
                'updated_at' => '2025-06-18 16:42:19',
            ),
            14 => 
            array (
                'id' => 15,
                'firstname' => 'Josephine',
                'lastname' => 'Nohay',
                'middlename' => 'Bejoc',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123458888',
                'avatar' => 'jbn0806.jpg',
                'signature' => 'jbn0806.png',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 15,
                'created_at' => '2025-06-18 09:46:59',
                'updated_at' => '2025-06-18 17:01:02',
            ),
            15 => 
            array (
                'id' => 16,
                'firstname' => 'Thelma',
                'lastname' => 'Diego',
                'middlename' => 'Emata',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456654',
                'avatar' => 'ted0417.jpg',
                'signature' => 'ted0417.png',
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 16,
                'created_at' => '2025-06-18 09:47:00',
                'updated_at' => '2025-06-18 16:55:20',
            ),
            16 => 
            array (
                'id' => 17,
                'firstname' => 'Teffanie Mae',
                'lastname' => 'Catalya',
                'middlename' => 'Madrazo',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456321',
                'avatar' => 'tmc0515.jpg',
                'signature' => 'tmc0515.jpg',
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 17,
                'created_at' => '2025-06-18 09:47:00',
                'updated_at' => '2025-06-18 16:54:47',
            ),
            17 => 
            array (
                'id' => 18,
                'firstname' => 'Sheila',
                'lastname' => 'Bernardo',
                'middlename' => 'Salenga',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'ssb1121.jpg',
                'signature' => 'ssb1121.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 18,
                'created_at' => '2025-06-18 09:47:00',
                'updated_at' => '2025-06-18 09:47:00',
            ),
            18 => 
            array (
                'id' => 19,
                'firstname' => 'Cris-angelo',
                'lastname' => 'Prieto',
                'middlename' => 'Busania',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'cbp1205.jpg',
                'signature' => 'cbp1205.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 19,
                'created_at' => '2025-06-18 09:47:01',
                'updated_at' => '2025-06-18 09:47:01',
            ),
            19 => 
            array (
                'id' => 20,
                'firstname' => 'Jennifer',
                'lastname' => 'Pidor',
                'middlename' => 'Alcazar',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123412345',
                'avatar' => 'jap0108.jpg',
                'signature' => 'jap0108.png',
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 20,
                'created_at' => '2025-06-18 09:47:01',
                'updated_at' => '2025-06-18 17:06:28',
            ),
            20 => 
            array (
                'id' => 21,
                'firstname' => 'John Kenneth',
                'lastname' => 'Cabral',
                'middlename' => 'De Asis',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456783',
                'avatar' => 'jdc0605.jpg',
                'signature' => 'jdc0605.png',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 21,
                'created_at' => '2025-06-18 09:47:01',
                'updated_at' => '2025-06-18 16:52:26',
            ),
            21 => 
            array (
                'id' => 22,
                'firstname' => 'Carlo Syl',
                'lastname' => 'Quinte',
                'middlename' => 'Labuca',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'clq1214.jpg',
                'signature' => 'clq1214.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 22,
                'created_at' => '2025-06-18 09:47:02',
                'updated_at' => '2025-06-18 09:47:02',
            ),
            22 => 
            array (
                'id' => 23,
                'firstname' => 'Jeyzel',
                'lastname' => 'Aparri',
                'middlename' => 'Perez',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456785',
                'avatar' => 'jpa1101.jpg',
                'signature' => 'jpa1101.jpg',
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 23,
                'created_at' => '2025-06-18 09:47:02',
                'updated_at' => '2025-06-18 16:35:58',
            ),
            23 => 
            array (
                'id' => 24,
                'firstname' => 'Nuhman',
                'lastname' => 'Aljani',
                'middlename' => 'Mahang',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456782',
                'avatar' => 'nma0601.png',
                'signature' => 'nma0601.png',
                'marital_id' => 2,
                'religion_id' => 20,
                'blood_id' => 7,
                'user_id' => 24,
                'created_at' => '2025-06-18 09:47:03',
                'updated_at' => '2025-06-20 09:23:07',
            ),
            24 => 
            array (
                'id' => 25,
                'firstname' => 'Julius',
                'lastname' => 'Fojas',
                'middlename' => 'Taghap',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123451234',
                'avatar' => 'jtf0723.jpg',
                'signature' => 'jtf0723.png',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 25,
                'created_at' => '2025-06-18 09:47:03',
                'updated_at' => '2025-06-18 16:56:35',
            ),
            25 => 
            array (
                'id' => 26,
                'firstname' => 'Marilyn Ann',
                'lastname' => 'Bueno',
                'middlename' => 'Caldito',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'mcb0107.jpg',
                'signature' => 'mcb0107.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 26,
                'created_at' => '2025-06-18 09:47:03',
                'updated_at' => '2025-06-18 09:47:03',
            ),
            26 => 
            array (
                'id' => 27,
                'firstname' => 'Enrique',
                'lastname' => 'Mariano',
                'middlename' => 'Magnaye',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'emm0715.jpg',
                'signature' => 'emm0715.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 27,
                'created_at' => '2025-06-18 09:47:04',
                'updated_at' => '2025-06-18 09:47:04',
            ),
            27 => 
            array (
                'id' => 28,
                'firstname' => 'Sheryl',
                'lastname' => 'Jovenal',
                'middlename' => 'Flores',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123413246',
                'avatar' => 'sfj0919.jpg',
                'signature' => 'sfj0919.jpg',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 28,
                'created_at' => '2025-06-18 09:47:04',
                'updated_at' => '2025-06-19 17:09:06',
            ),
            28 => 
            array (
                'id' => 29,
                'firstname' => 'Gerardo',
                'lastname' => 'Parot',
                'middlename' => 'Fajardo',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123458764',
                'avatar' => 'gfp0608.jpg',
                'signature' => 'gfp0608.png',
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 29,
                'created_at' => '2025-06-18 09:47:05',
                'updated_at' => '2025-06-18 17:05:52',
            ),
            29 => 
            array (
                'id' => 30,
                'firstname' => 'Ingrid',
                'lastname' => 'Abella-colcol',
                'middlename' => 'Tagaro',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456781',
                'avatar' => 'itac0107.png',
                'signature' => 'itac0107.png',
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 30,
                'created_at' => '2025-06-18 09:47:05',
                'updated_at' => '2025-06-18 16:20:59',
            ),
            30 => 
            array (
                'id' => 31,
                'firstname' => 'Marc',
                'lastname' => 'Cachin',
                'middlename' => 'Guimbarda',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456111',
                'avatar' => 'mgc0312.jpg',
                'signature' => 'mgc0312.png',
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 31,
                'created_at' => '2025-06-18 09:47:05',
                'updated_at' => '2025-06-18 16:53:07',
            ),
            31 => 
            array (
                'id' => 32,
                'firstname' => 'Christian Carl',
                'lastname' => 'Resente',
                'middlename' => 'Rivera',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123443215',
                'avatar' => 'crr0918.jpg',
                'signature' => 'crr0918.jpg',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 32,
                'created_at' => '2025-06-18 09:47:06',
                'updated_at' => '2025-06-18 17:07:44',
            ),
            32 => 
            array (
                'id' => 33,
                'firstname' => 'Jelyn',
                'lastname' => 'Bayonas',
                'middlename' => 'O',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456733',
                'avatar' => 'job0518.jpg',
                'signature' => 'job0518.png',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 33,
                'created_at' => '2025-06-18 09:47:06',
                'updated_at' => '2025-06-18 16:50:52',
            ),
            33 => 
            array (
                'id' => 34,
                'firstname' => 'Kristine Mae',
                'lastname' => 'Sarita',
                'middlename' => 'Rodriguez',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123457777',
                'avatar' => 'krs0127.jpg',
                'signature' => 'krs0127.png',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 34,
                'created_at' => '2025-06-18 09:47:07',
                'updated_at' => '2025-06-18 17:09:16',
            ),
            34 => 
            array (
                'id' => 35,
                'firstname' => 'Marielle',
                'lastname' => 'Atilano',
                'middlename' => 'Ramirez',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'mra1218.jpg',
                'signature' => 'mra1218.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 35,
                'created_at' => '2025-06-18 09:47:07',
                'updated_at' => '2025-06-18 09:47:07',
            ),
            35 => 
            array (
                'id' => 36,
                'firstname' => 'Mark Vincent',
                'lastname' => 'Baliña',
                'middlename' => 'Jayson',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456722',
                'avatar' => 'mjbalina.png',
                'signature' => 'mjbalina.png',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 36,
                'created_at' => '2025-06-18 09:47:07',
                'updated_at' => '2025-06-18 16:50:11',
            ),
            36 => 
            array (
                'id' => 37,
                'firstname' => 'Ronie',
                'lastname' => 'Dinawanao',
                'middlename' => 'Ricablanca',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'rrd0613.jpg',
                'signature' => 'rrd0613.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 37,
                'created_at' => '2025-06-18 09:47:08',
                'updated_at' => '2025-06-18 09:47:08',
            ),
            37 => 
            array (
                'id' => 38,
                'firstname' => 'Allan Geion',
                'lastname' => 'Legaspi',
                'middlename' => 'Pagayonan',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123454444',
                'avatar' => 'apl0318.jpg',
                'signature' => 'apl0318.png',
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 38,
                'created_at' => '2025-06-18 09:47:08',
                'updated_at' => '2025-06-18 16:58:02',
            ),
            38 => 
            array (
                'id' => 39,
                'firstname' => 'Cleypart',
                'lastname' => 'Braca',
                'middlename' => 'G',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'cgb0323.png',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 39,
                'created_at' => '2025-06-18 09:47:09',
                'updated_at' => '2025-06-18 09:47:09',
            ),
            39 => 
            array (
                'id' => 40,
                'firstname' => 'Kevin Karl',
                'lastname' => 'Ramiso',
                'middlename' => 'Ramos',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'krr1109.jpg',
                'signature' => 'krr1109.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 40,
                'created_at' => '2025-06-18 09:47:09',
                'updated_at' => '2025-06-18 09:47:09',
            ),
            40 => 
            array (
                'id' => 41,
                'firstname' => 'Jun Carlo',
                'lastname' => 'Tangon',
                'middlename' => 'B',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'jbt0716.JPG',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 41,
                'created_at' => '2025-06-18 09:47:09',
                'updated_at' => '2025-06-18 09:47:09',
            ),
            41 => 
            array (
                'id' => 42,
                'firstname' => 'Armando',
                'lastname' => 'Fernandez',
                'middlename' => 'A',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'aaf0206.png',
                'signature' => 'aaf0206.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 42,
                'created_at' => '2025-06-18 09:47:10',
                'updated_at' => '2025-06-18 09:47:10',
            ),
            42 => 
            array (
                'id' => 43,
                'firstname' => 'Analyn',
                'lastname' => 'Sajiin',
                'middlename' => 'Lasola',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'als0205.png',
                'signature' => 'als0205.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 43,
                'created_at' => '2025-06-18 09:47:10',
                'updated_at' => '2025-06-18 09:47:10',
            ),
            43 => 
            array (
                'id' => 44,
                'firstname' => 'Kim',
                'lastname' => 'Carumba',
                'middlename' => 'Ricaborda',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456222',
                'avatar' => 'krc0108.png',
                'signature' => 'krc0108.png',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 44,
                'created_at' => '2025-06-18 09:47:10',
                'updated_at' => '2025-06-18 16:53:57',
            ),
            44 => 
            array (
                'id' => 45,
                'firstname' => 'Charisa Mae',
                'lastname' => 'Bait-it',
                'middlename' => 'Malig-on',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'cmb0322.png',
                'signature' => 'cmb0322.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 45,
                'created_at' => '2025-06-18 09:47:11',
                'updated_at' => '2025-06-18 09:47:11',
            ),
            45 => 
            array (
                'id' => 46,
                'firstname' => 'Judilyn',
                'lastname' => 'Alvarez',
                'middlename' => 'Enoferio',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'jea1124.png',
                'signature' => 'jea1124.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 46,
                'created_at' => '2025-06-18 09:47:11',
                'updated_at' => '2025-06-18 09:47:11',
            ),
            46 => 
            array (
                'id' => 47,
                'firstname' => 'Jan Melvin',
                'lastname' => 'Vallejo',
                'middlename' => 'D.',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123451212',
                'avatar' => 'jdv0703.jpg',
                'signature' => 'jdv0703.png',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 47,
                'created_at' => '2025-06-18 09:47:12',
                'updated_at' => '2025-06-19 17:10:55',
            ),
            47 => 
            array (
                'id' => 48,
                'firstname' => 'Arman',
                'lastname' => 'Aquino',
                'middlename' => 'Elogsong',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'aea0710.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 48,
                'created_at' => '2025-06-18 09:47:12',
                'updated_at' => '2025-06-18 09:47:12',
            ),
            48 => 
            array (
                'id' => 49,
                'firstname' => 'Herson Santiago',
                'lastname' => 'Fernando Jr',
                'middlename' => 'S',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'hsf0406.jpg',
                'signature' => 'hsf0406.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 49,
                'created_at' => '2025-06-18 09:47:13',
                'updated_at' => '2025-06-18 09:47:13',
            ),
            49 => 
            array (
                'id' => 50,
                'firstname' => 'Ian',
                'lastname' => 'Avenido',
                'middlename' => 'C',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'ica0706.jpg',
                'signature' => 'ica0706.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 50,
                'created_at' => '2025-06-18 09:47:13',
                'updated_at' => '2025-06-18 09:47:13',
            ),
            50 => 
            array (
                'id' => 51,
                'firstname' => 'Dores',
                'lastname' => 'Gabo',
                'middlename' => 'Calago',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123454311',
                'avatar' => 'dbc0220.png',
                'signature' => 'dbc0220.png',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 51,
                'created_at' => '2025-06-18 09:47:14',
                'updated_at' => '2025-06-18 16:57:13',
            ),
            51 => 
            array (
                'id' => 52,
                'firstname' => 'John Ken',
                'lastname' => 'Esmas',
                'middlename' => 'Yamuta',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456987',
                'avatar' => 'jye0624.jpg',
                'signature' => 'jye0624.jpg',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 52,
                'created_at' => '2025-06-18 09:47:14',
                'updated_at' => '2025-06-18 16:55:54',
            ),
            52 => 
            array (
                'id' => 53,
                'firstname' => 'Al Jeffrey',
                'lastname' => 'Sardan',
                'middlename' => 'Bregondot',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'abs0530.png',
                'signature' => 'abs0530.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 53,
                'created_at' => '2025-06-18 09:47:14',
                'updated_at' => '2025-06-18 09:47:14',
            ),
            53 => 
            array (
                'id' => 54,
                'firstname' => 'Stenel Rizza',
                'lastname' => 'Alegre',
                'middlename' => 'Villanueva',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'sva0308.png',
                'signature' => 'sva0308.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 54,
                'created_at' => '2025-06-18 09:47:15',
                'updated_at' => '2025-06-18 09:47:15',
            ),
            54 => 
            array (
                'id' => 55,
                'firstname' => 'Tara Mae',
                'lastname' => 'Balla',
                'middlename' => 'Burillo',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'tbb1204.png',
                'signature' => 'tbb1204.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 55,
                'created_at' => '2025-06-18 09:47:15',
                'updated_at' => '2025-06-18 09:47:15',
            ),
            55 => 
            array (
                'id' => 56,
                'firstname' => 'Ellyssa Mae',
                'lastname' => 'Pendergat',
                'middlename' => 'A',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'eap1011.png',
                'signature' => 'eap1011.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 56,
                'created_at' => '2025-06-18 09:47:15',
                'updated_at' => '2025-06-18 09:47:15',
            ),
            56 => 
            array (
                'id' => 57,
                'firstname' => 'Herma Joyce',
                'lastname' => 'Alburo',
                'middlename' => 'Triambulo',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123422111',
                'avatar' => 'hta0316.jpg',
                'signature' => 'hta0316.png',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 57,
                'created_at' => '2025-06-18 09:47:16',
                'updated_at' => '2025-06-19 17:01:54',
            ),
            57 => 
            array (
                'id' => 58,
                'firstname' => 'Jerves',
                'lastname' => 'Dalde',
                'middlename' => 'Zamora',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'jzd0318.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 58,
                'created_at' => '2025-06-18 09:47:16',
                'updated_at' => '2025-06-18 09:47:16',
            ),
            58 => 
            array (
                'id' => 59,
                'firstname' => 'Dreamly',
                'lastname' => 'Sumangil',
                'middlename' => 'Pajarito',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'dps0615.png',
                'signature' => 'dps0615.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 59,
                'created_at' => '2025-06-18 09:47:17',
                'updated_at' => '2025-06-18 09:47:17',
            ),
            59 => 
            array (
                'id' => 60,
                'firstname' => 'Danilo',
                'lastname' => 'Bation',
                'middlename' => 'S',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'dsb1118.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 60,
                'created_at' => '2025-06-18 09:47:17',
                'updated_at' => '2025-06-18 09:47:17',
            ),
            60 => 
            array (
                'id' => 61,
                'firstname' => 'Benito',
                'lastname' => 'Tajada',
                'middlename' => 'J',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'bjt0414.jpg',
                'signature' => 'bjt0414.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 61,
                'created_at' => '2025-06-18 09:47:17',
                'updated_at' => '2025-06-18 09:47:17',
            ),
            61 => 
            array (
                'id' => 62,
                'firstname' => 'Joemar',
                'lastname' => 'Anghag',
                'middlename' => 'Bongcawel',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456432',
                'avatar' => 'jba1006.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 62,
                'created_at' => '2025-06-18 09:47:18',
                'updated_at' => '2025-06-19 17:06:09',
            ),
            62 => 
            array (
                'id' => 63,
                'firstname' => 'Joefry',
                'lastname' => 'Fernando',
                'middlename' => 'Pon',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'jpf0611.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 63,
                'created_at' => '2025-06-18 09:47:18',
                'updated_at' => '2025-06-18 09:47:18',
            ),
            63 => 
            array (
                'id' => 64,
                'firstname' => 'Jecil Joy',
                'lastname' => 'Querubin',
                'middlename' => 'Berdin',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'jbq0820.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 64,
                'created_at' => '2025-06-18 09:47:19',
                'updated_at' => '2025-06-18 09:47:19',
            ),
            64 => 
            array (
                'id' => 65,
                'firstname' => 'Albertson',
                'lastname' => 'Patenio',
                'middlename' => 'T',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'atp-0610.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 65,
                'created_at' => '2025-06-18 09:47:19',
                'updated_at' => '2025-06-18 09:47:19',
            ),
            65 => 
            array (
                'id' => 66,
                'firstname' => 'Marvin',
                'lastname' => 'Basira',
                'middlename' => 'Bacus',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'mbb0704.jpg',
                'signature' => 'mbb0704.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 66,
                'created_at' => '2025-06-18 09:47:19',
                'updated_at' => '2025-06-18 09:47:19',
            ),
            66 => 
            array (
                'id' => 67,
                'firstname' => 'Alma Fe',
                'lastname' => 'Albarico',
                'middlename' => 'Habla',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'aha0201.jpg',
                'signature' => 'aha0201.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 67,
                'created_at' => '2025-06-18 09:47:20',
                'updated_at' => '2025-06-18 09:47:20',
            ),
            67 => 
            array (
                'id' => 68,
                'firstname' => 'Macario Jr.',
                'lastname' => 'Hilaos',
                'middlename' => 'Monterola',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'mmh0824.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 68,
                'created_at' => '2025-06-18 09:47:20',
                'updated_at' => '2025-06-18 09:47:20',
            ),
            68 => 
            array (
                'id' => 69,
                'firstname' => 'Cindy',
                'lastname' => 'Obnimaga',
                'middlename' => 'Jauculan',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'csj0629.jpg',
                'signature' => 'csj0629.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 69,
                'created_at' => '2025-06-18 09:47:21',
                'updated_at' => '2025-06-18 09:47:21',
            ),
            69 => 
            array (
                'id' => 70,
                'firstname' => 'Shiryll',
                'lastname' => 'Garcia',
                'middlename' => 'Bantilan',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'sbg0817.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 70,
                'created_at' => '2025-06-18 09:47:21',
                'updated_at' => '2025-06-18 09:47:21',
            ),
            70 => 
            array (
                'id' => 71,
                'firstname' => 'Roger Dave',
                'lastname' => 'Gramatica',
                'middlename' => 'Fabian',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'rfg0225.png',
                'signature' => 'rfg0225.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 71,
                'created_at' => '2025-06-18 09:47:21',
                'updated_at' => '2025-06-18 09:47:21',
            ),
            71 => 
            array (
                'id' => 72,
                'firstname' => 'Eva Mae',
                'lastname' => 'Villabeto',
                'middlename' => 'A',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'eva0505.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 72,
                'created_at' => '2025-06-18 09:47:22',
                'updated_at' => '2025-06-18 09:47:22',
            ),
            72 => 
            array (
                'id' => 73,
                'firstname' => 'Ruish Nova',
                'lastname' => 'Jazmin',
                'middlename' => 'Cabico',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 73,
                'created_at' => '2025-06-18 09:47:22',
                'updated_at' => '2025-06-18 09:47:22',
            ),
            73 => 
            array (
                'id' => 74,
                'firstname' => 'Jeffrey',
                'lastname' => 'Balugo',
                'middlename' => 'T',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 74,
                'created_at' => '2025-06-18 09:47:23',
                'updated_at' => '2025-06-18 09:47:23',
            ),
            74 => 
            array (
                'id' => 75,
                'firstname' => 'Josef Kyle',
                'lastname' => 'Lugo',
                'middlename' => 'Obnimaga',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'jol0917.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 75,
                'created_at' => '2025-06-18 09:47:23',
                'updated_at' => '2025-06-18 09:47:23',
            ),
            75 => 
            array (
                'id' => 76,
                'firstname' => 'Christine',
                'lastname' => 'Zamora',
                'middlename' => 'Aguilar',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'caz0306.PNG',
                'signature' => 'caz0306.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 76,
                'created_at' => '2025-06-18 09:47:23',
                'updated_at' => '2025-06-18 09:47:23',
            ),
            76 => 
            array (
                'id' => 77,
                'firstname' => 'Miguel Louis',
                'lastname' => 'Calunod',
                'middlename' => 'Atilano',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 77,
                'created_at' => '2025-06-18 09:47:24',
                'updated_at' => '2025-06-18 09:47:24',
            ),
            77 => 
            array (
                'id' => 78,
                'firstname' => 'Princess Kate',
                'lastname' => 'Gerundio',
                'middlename' => '-',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'pkg0326.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 78,
                'created_at' => '2025-06-18 09:47:24',
                'updated_at' => '2025-06-18 09:47:24',
            ),
            78 => 
            array (
                'id' => 79,
                'firstname' => 'Jake Syrel',
                'lastname' => 'Palma',
                'middlename' => 'Virtudazo',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'jvp0315.png',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 79,
                'created_at' => '2025-06-18 09:47:24',
                'updated_at' => '2025-06-18 09:47:24',
            ),
            79 => 
            array (
                'id' => 80,
                'firstname' => 'Jeron',
                'lastname' => 'Elloran',
                'middlename' => 'Allandraquez',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'jae1204.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 80,
                'created_at' => '2025-06-18 09:47:25',
                'updated_at' => '2025-06-18 09:47:25',
            ),
            80 => 
            array (
                'id' => 81,
                'firstname' => 'Emierose',
                'lastname' => 'Empas',
                'middlename' => 'Castanares',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 81,
                'created_at' => '2025-06-18 09:47:25',
                'updated_at' => '2025-06-18 09:47:25',
            ),
            81 => 
            array (
                'id' => 82,
                'firstname' => 'Shiela Mari',
                'lastname' => 'Ramos',
                'middlename' => 'Cruz',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'scr1022.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 82,
                'created_at' => '2025-06-18 09:47:26',
                'updated_at' => '2025-06-18 09:47:26',
            ),
            82 => 
            array (
                'id' => 83,
                'firstname' => 'Jesus',
                'lastname' => 'Reyes',
                'middlename' => 'E',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 83,
                'created_at' => '2025-06-18 09:47:26',
                'updated_at' => '2025-06-18 09:47:26',
            ),
            83 => 
            array (
                'id' => 84,
                'firstname' => 'Macario',
                'lastname' => 'Hilaos',
                'middlename' => 'M',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 84,
                'created_at' => '2025-06-18 09:47:26',
                'updated_at' => '2025-06-18 09:47:26',
            ),
            84 => 
            array (
                'id' => 85,
                'firstname' => 'Wilfredo',
                'lastname' => 'Alvarez',
                'middlename' => 'P',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 85,
                'created_at' => '2025-06-18 09:47:27',
                'updated_at' => '2025-06-18 09:47:27',
            ),
            85 => 
            array (
                'id' => 86,
                'firstname' => 'Anthony',
                'lastname' => 'Santos',
                'middlename' => 'C',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 86,
                'created_at' => '2025-06-18 09:47:27',
                'updated_at' => '2025-06-18 09:47:27',
            ),
            86 => 
            array (
                'id' => 87,
                'firstname' => 'Gian Carlo',
                'lastname' => 'Acejas',
                'middlename' => 'C',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 87,
                'created_at' => '2025-06-18 09:47:27',
                'updated_at' => '2025-06-18 09:47:27',
            ),
            87 => 
            array (
                'id' => 88,
                'firstname' => 'Ben Joseph',
                'lastname' => 'Carpio',
                'middlename' => 'Comendador',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 88,
                'created_at' => '2025-06-18 09:47:28',
                'updated_at' => '2025-06-18 09:47:28',
            ),
            88 => 
            array (
                'id' => 89,
                'firstname' => 'Fatima Wahida',
                'lastname' => 'Himpon',
                'middlename' => 'Jamang',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 89,
                'created_at' => '2025-06-18 09:47:28',
                'updated_at' => '2025-06-18 09:47:28',
            ),
            89 => 
            array (
                'id' => 90,
                'firstname' => 'Ma Ellaine',
                'lastname' => 'Rayman',
                'middlename' => 'Masamayor',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 90,
                'created_at' => '2025-06-18 09:47:29',
                'updated_at' => '2025-06-18 09:47:29',
            ),
            90 => 
            array (
                'id' => 91,
                'firstname' => 'Reniel',
                'lastname' => 'Tumacas',
                'middlename' => 'Bentoy',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 91,
                'created_at' => '2025-06-18 09:47:29',
                'updated_at' => '2025-06-18 09:47:29',
            ),
            91 => 
            array (
                'id' => 92,
                'firstname' => 'Anna Mae',
                'lastname' => 'Francisco',
                'middlename' => 'Cutab',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 92,
                'created_at' => '2025-06-18 09:47:29',
                'updated_at' => '2025-06-18 09:47:29',
            ),
            92 => 
            array (
                'id' => 93,
                'firstname' => 'Vanessa',
                'lastname' => 'Delos Santos',
                'middlename' => 'Yuldan',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 93,
                'created_at' => '2025-06-18 09:47:30',
                'updated_at' => '2025-06-18 09:47:30',
            ),
            93 => 
            array (
                'id' => 94,
                'firstname' => 'Chavy Jill',
                'lastname' => 'Halasan',
                'middlename' => 'Carbonera',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 94,
                'created_at' => '2025-06-18 09:47:30',
                'updated_at' => '2025-06-18 09:47:30',
            ),
            94 => 
            array (
                'id' => 95,
                'firstname' => 'Mitzi Jeanette',
                'lastname' => 'Cudiera',
                'middlename' => 'Laping',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 95,
                'created_at' => '2025-06-18 09:47:30',
                'updated_at' => '2025-06-18 09:47:30',
            ),
            95 => 
            array (
                'id' => 96,
                'firstname' => 'Gretchen',
                'lastname' => 'Manangan',
                'middlename' => 'Dońos',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 96,
                'created_at' => '2025-06-18 09:47:31',
                'updated_at' => '2025-06-18 09:47:31',
            ),
            96 => 
            array (
                'id' => 97,
                'firstname' => 'Rufie Mae',
                'lastname' => 'Gansan',
                'middlename' => 'Sumpiao',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 97,
                'created_at' => '2025-06-18 09:47:31',
                'updated_at' => '2025-06-18 09:47:31',
            ),
            97 => 
            array (
                'id' => 98,
                'firstname' => 'Nelida',
                'lastname' => 'Jada',
                'middlename' => 'A',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 98,
                'created_at' => '2025-06-18 09:47:31',
                'updated_at' => '2025-06-18 09:47:31',
            ),
            98 => 
            array (
                'id' => 99,
                'firstname' => 'Angelica Joy',
                'lastname' => 'Tubo',
                'middlename' => 'Ando',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 99,
                'created_at' => '2025-06-18 09:47:32',
                'updated_at' => '2025-06-18 09:47:32',
            ),
            99 => 
            array (
                'id' => 100,
                'firstname' => 'Mariefer',
                'lastname' => 'Utal',
                'middlename' => 'Talitod',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'mtu0104.jpg',
                'signature' => 'mtu0104.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 100,
                'created_at' => '2025-06-18 09:47:32',
                'updated_at' => '2025-06-18 09:47:32',
            ),
            100 => 
            array (
                'id' => 101,
                'firstname' => 'Aubrey',
                'lastname' => 'Amparo',
                'middlename' => 'Apduhan',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 101,
                'created_at' => '2025-06-18 09:47:33',
                'updated_at' => '2025-06-18 09:47:33',
            ),
            101 => 
            array (
                'id' => 102,
                'firstname' => 'Zara',
                'lastname' => 'Muyong',
                'middlename' => 'Saali',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'zsm0511.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 102,
                'created_at' => '2025-06-18 09:47:33',
                'updated_at' => '2025-06-18 09:47:33',
            ),
            102 => 
            array (
                'id' => 103,
                'firstname' => 'Oni Angelo',
                'lastname' => 'Gomez',
                'middlename' => 'Natividad',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'ong0519.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 103,
                'created_at' => '2025-06-18 09:47:33',
                'updated_at' => '2025-06-18 09:47:33',
            ),
            103 => 
            array (
                'id' => 104,
                'firstname' => 'Camil Joyce',
                'lastname' => 'Chiong',
                'middlename' => 'Delos Reyes',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 104,
                'created_at' => '2025-06-18 09:47:34',
                'updated_at' => '2025-06-18 09:47:34',
            ),
            104 => 
            array (
                'id' => 105,
                'firstname' => 'Adrian Jude',
                'lastname' => 'Gutierrez',
                'middlename' => 'Jacinto',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'ajg1125.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 105,
                'created_at' => '2025-06-18 09:47:34',
                'updated_at' => '2025-06-18 09:47:34',
            ),
            105 => 
            array (
                'id' => 106,
                'firstname' => 'Julienne',
                'lastname' => 'Sagut',
                'middlename' => 'Brigole',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'jbs1015.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 106,
                'created_at' => '2025-06-18 09:47:35',
                'updated_at' => '2025-06-18 09:47:35',
            ),
            106 => 
            array (
                'id' => 107,
                'firstname' => 'Kyle Angelo',
                'lastname' => 'Adas',
                'middlename' => 'Gealon',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 107,
                'created_at' => '2025-06-18 09:47:35',
                'updated_at' => '2025-06-18 09:47:35',
            ),
            107 => 
            array (
                'id' => 108,
                'firstname' => 'Joan Carmela',
                'lastname' => 'Casquelo',
                'middlename' => 'Angeles',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'signature.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 108,
                'created_at' => '2025-06-18 09:47:35',
                'updated_at' => '2025-06-18 09:47:35',
            ),
            108 => 
            array (
                'id' => 109,
                'firstname' => 'Sherven Geneil',
                'lastname' => 'Salabit',
                'middlename' => 'Rodriguez',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'srs0305.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 109,
                'created_at' => '2025-06-18 09:47:36',
                'updated_at' => '2025-06-18 09:47:36',
            ),
            109 => 
            array (
                'id' => 110,
                'firstname' => 'Raymond',
                'lastname' => 'Clemente',
                'middlename' => 'Rabina',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'rrc1002.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 110,
                'created_at' => '2025-06-18 09:47:36',
                'updated_at' => '2025-06-18 09:47:36',
            ),
            110 => 
            array (
                'id' => 111,
                'firstname' => 'Iolette Beatriz',
                'lastname' => 'Babas',
                'middlename' => 'Morales',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'imb0927.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 111,
                'created_at' => '2025-06-18 09:47:36',
                'updated_at' => '2025-06-18 09:47:36',
            ),
            111 => 
            array (
                'id' => 112,
                'firstname' => 'Larra Andrea',
                'lastname' => 'Anastacio',
                'middlename' => 'Mulato',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'lma0414.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 112,
                'created_at' => '2025-06-18 09:47:37',
                'updated_at' => '2025-06-18 09:47:37',
            ),
            112 => 
            array (
                'id' => 113,
                'firstname' => 'Ardlee',
                'lastname' => 'Natividad',
                'middlename' => 'Ruiz',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'arn1020.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 113,
                'created_at' => '2025-06-18 09:47:37',
                'updated_at' => '2025-06-18 09:47:37',
            ),
            113 => 
            array (
                'id' => 114,
                'firstname' => 'Kenneth',
                'lastname' => 'Briones',
                'middlename' => 'Hamsirani',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'khb1124.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 114,
                'created_at' => '2025-06-18 09:47:37',
                'updated_at' => '2025-06-18 09:47:37',
            ),
            114 => 
            array (
                'id' => 115,
                'firstname' => 'Aigel',
                'lastname' => 'Martinez',
                'middlename' => 'Anastacio',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'aam0920.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 115,
                'created_at' => '2025-06-18 09:47:38',
                'updated_at' => '2025-06-18 09:47:38',
            ),
            115 => 
            array (
                'id' => 116,
                'firstname' => 'Rachel',
                'lastname' => 'Rubio',
                'middlename' => 'Villanueva',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'rvr1202.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 116,
                'created_at' => '2025-06-18 09:47:38',
                'updated_at' => '2025-06-18 09:47:38',
            ),
            116 => 
            array (
                'id' => 117,
                'firstname' => 'Jon Brett',
                'lastname' => 'Madarang',
                'middlename' => 'N/a',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'jbm1012.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 117,
                'created_at' => '2025-06-18 09:47:39',
                'updated_at' => '2025-06-18 09:47:39',
            ),
            117 => 
            array (
                'id' => 118,
                'firstname' => 'Noellance Jane',
                'lastname' => 'Diaz',
                'middlename' => 'Jayson',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'njd0624.png',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 118,
                'created_at' => '2025-06-18 09:47:39',
                'updated_at' => '2025-06-18 09:47:39',
            ),
            118 => 
            array (
                'id' => 119,
                'firstname' => 'Andrei',
                'lastname' => 'Rabon',
                'middlename' => 'Rojas',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-06-18',
                'contact_no' => '09123456789',
                'avatar' => 'avatar.jpg',
                'signature' => 'arr0921.jpg',
                'marital_id' => 1,
                'religion_id' => 19,
                'blood_id' => 1,
                'user_id' => 119,
                'created_at' => '2025-06-18 09:47:39',
                'updated_at' => '2025-06-18 09:47:39',
            ),
            119 => 
            array (
                'id' => 120,
                'firstname' => 'Danica Mae',
                'lastname' => 'Sta. Teresa',
                'middlename' => 'Vicente',
                'suffix' => NULL,
                'sex' => 'Female',
                'birthdate' => '2025-07-07',
                'contact_no' => '09123654789',
                'avatar' => 'avatar.jpg',
                'signature' => NULL,
                'marital_id' => 2,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 120,
                'created_at' => '2025-06-18 09:54:52',
                'updated_at' => '2025-06-18 09:54:52',
            ),
            120 => 
            array (
                'id' => 121,
                'firstname' => 'Richard',
                'lastname' => 'Araneta',
                'middlename' => 'Rojas',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-11-14',
                'contact_no' => '09123654879',
                'avatar' => 'avatar.jpg',
                'signature' => NULL,
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 121,
                'created_at' => '2025-06-18 10:35:17',
                'updated_at' => '2025-06-18 10:35:17',
            ),
            121 => 
            array (
                'id' => 122,
                'firstname' => 'Romeo',
                'lastname' => 'Ligalig',
                'middlename' => 'M',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-05-03',
                'contact_no' => '09321654987',
                'avatar' => 'avatar.jpg',
                'signature' => NULL,
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 122,
                'created_at' => '2025-06-18 10:36:38',
                'updated_at' => '2025-06-18 10:36:38',
            ),
            122 => 
            array (
                'id' => 123,
                'firstname' => 'Melodrino',
                'lastname' => 'Estabillo',
                'middlename' => 'Revilla',
                'suffix' => NULL,
                'sex' => 'Male',
                'birthdate' => '2025-10-14',
                'contact_no' => '09123654963',
                'avatar' => 'avatar.jpg',
                'signature' => NULL,
                'marital_id' => 3,
                'religion_id' => 19,
                'blood_id' => 7,
                'user_id' => 123,
                'created_at' => '2025-06-18 10:38:09',
                'updated_at' => '2025-06-18 10:38:09',
            ),
        ));

        
    }
}